-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accel_top_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_width : IN STD_LOGIC_VECTOR (31 downto 0);
    bound : IN STD_LOGIC_VECTOR (63 downto 0);
    input_0_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_0_0_ce0 : OUT STD_LOGIC;
    input_0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_0_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_0_1_ce0 : OUT STD_LOGIC;
    input_0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_1_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_1_0_ce0 : OUT STD_LOGIC;
    input_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_1_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_1_1_ce0 : OUT STD_LOGIC;
    input_1_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_r_ce1 : OUT STD_LOGIC;
    output_r_we1 : OUT STD_LOGIC;
    output_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of accel_top_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln25_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln38_fu_261_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln38_reg_386 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln38_reg_386_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln34_fu_294_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln34_reg_391 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln35_fu_308_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln35_reg_397 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln29_fu_253_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln38_fu_316_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ow_fu_56 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln26_fu_267_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal oh_fu_60 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln25_1_fu_207_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_fu_64 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln25_1_fu_184_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_fu_170_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln26_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln25_fu_193_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln29_1_fu_219_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln29_fu_215_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln25_fu_199_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_223_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln29_3_fu_243_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln29_fu_247_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_231_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln29_2_fu_239_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln1081_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1081_1_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1081_2_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component accel_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component accel_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_64 <= ap_const_lv64_0;
                elsif (((icmp_ln25_fu_179_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_64 <= add_ln25_1_fu_184_p2;
                end if;
            end if; 
        end if;
    end process;

    oh_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    oh_fu_60 <= ap_const_lv32_0;
                elsif (((icmp_ln25_fu_179_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    oh_fu_60 <= select_ln25_1_fu_207_p3;
                end if;
            end if; 
        end if;
    end process;

    ow_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ow_fu_56 <= ap_const_lv11_0;
                elsif (((icmp_ln25_fu_179_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    ow_fu_56 <= add_ln26_fu_267_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln25_fu_179_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln38_reg_386 <= add_ln38_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln38_reg_386_pp0_iter2_reg <= add_ln38_reg_386;
                select_ln34_reg_391 <= select_ln34_fu_294_p3;
                select_ln35_reg_397 <= select_ln35_fu_308_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln25_1_fu_184_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_64) + unsigned(ap_const_lv64_1));
    add_ln25_fu_193_p2 <= std_logic_vector(unsigned(oh_fu_60) + unsigned(ap_const_lv32_1));
    add_ln26_fu_267_p2 <= std_logic_vector(unsigned(select_ln25_fu_199_p3) + unsigned(ap_const_lv11_1));
    add_ln29_fu_247_p2 <= std_logic_vector(unsigned(tmp_fu_223_p3) + unsigned(trunc_ln29_3_fu_243_p1));
    add_ln38_fu_261_p2 <= std_logic_vector(unsigned(tmp_3_fu_231_p3) + unsigned(trunc_ln29_2_fu_239_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln25_fu_179_p2)
    begin
        if (((icmp_ln25_fu_179_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1081_1_fu_302_p2 <= "1" when (signed(input_1_0_q0) > signed(input_1_1_q0)) else "0";
    icmp_ln1081_2_fu_320_p2 <= "1" when (signed(select_ln34_reg_391) > signed(select_ln35_reg_397)) else "0";
    icmp_ln1081_fu_288_p2 <= "1" when (signed(input_0_0_q0) > signed(input_0_1_q0)) else "0";
    icmp_ln25_fu_179_p2 <= "1" when (indvar_flatten_fu_64 = bound) else "0";
    icmp_ln26_fu_174_p2 <= "1" when (zext_ln26_fu_170_p1 = out_width) else "0";
    input_0_0_address0 <= zext_ln29_fu_253_p1(8 - 1 downto 0);

    input_0_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_0_0_ce0 <= ap_const_logic_1;
        else 
            input_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_0_1_address0 <= zext_ln29_fu_253_p1(8 - 1 downto 0);

    input_0_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_0_1_ce0 <= ap_const_logic_1;
        else 
            input_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_1_0_address0 <= zext_ln29_fu_253_p1(8 - 1 downto 0);

    input_1_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_1_0_ce0 <= ap_const_logic_1;
        else 
            input_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_1_1_address0 <= zext_ln29_fu_253_p1(8 - 1 downto 0);

    input_1_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_1_1_ce0 <= ap_const_logic_1;
        else 
            input_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_address1 <= zext_ln38_fu_316_p1(10 - 1 downto 0);

    output_r_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_r_ce1 <= ap_const_logic_1;
        else 
            output_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d1 <= 
        select_ln34_reg_391 when (icmp_ln1081_2_fu_320_p2(0) = '1') else 
        select_ln35_reg_397;

    output_r_we1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            output_r_we1 <= ap_const_logic_1;
        else 
            output_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln25_1_fu_207_p3 <= 
        add_ln25_fu_193_p2 when (icmp_ln26_fu_174_p2(0) = '1') else 
        oh_fu_60;
    select_ln25_fu_199_p3 <= 
        ap_const_lv11_0 when (icmp_ln26_fu_174_p2(0) = '1') else 
        ow_fu_56;
    select_ln34_fu_294_p3 <= 
        input_0_0_q0 when (icmp_ln1081_fu_288_p2(0) = '1') else 
        input_0_1_q0;
    select_ln35_fu_308_p3 <= 
        input_1_0_q0 when (icmp_ln1081_1_fu_302_p2(0) = '1') else 
        input_1_1_q0;
    tmp_3_fu_231_p3 <= (trunc_ln29_fu_215_p1 & ap_const_lv5_0);
    tmp_fu_223_p3 <= (trunc_ln29_1_fu_219_p1 & ap_const_lv4_0);
    trunc_ln29_1_fu_219_p1 <= select_ln25_1_fu_207_p3(4 - 1 downto 0);
    trunc_ln29_2_fu_239_p1 <= select_ln25_fu_199_p3(10 - 1 downto 0);
    trunc_ln29_3_fu_243_p1 <= select_ln25_fu_199_p3(8 - 1 downto 0);
    trunc_ln29_fu_215_p1 <= select_ln25_1_fu_207_p3(5 - 1 downto 0);
    zext_ln26_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ow_fu_56),32));
    zext_ln29_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_fu_247_p2),64));
    zext_ln38_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln38_reg_386_pp0_iter2_reg),64));
end behav;
