-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accel_top_maxpool_2x2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_0_0_ce0 : OUT STD_LOGIC;
    input_0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_0_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_0_1_ce0 : OUT STD_LOGIC;
    input_0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_1_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_1_0_ce0 : OUT STD_LOGIC;
    input_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_1_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_1_1_ce0 : OUT STD_LOGIC;
    input_1_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_r_ce1 : OUT STD_LOGIC;
    output_r_we1 : OUT STD_LOGIC;
    output_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_height : IN STD_LOGIC_VECTOR (31 downto 0);
    in_width : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of accel_top_maxpool_2x2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal out_height_fu_112_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_height_reg_189 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_width_fu_168_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_width_reg_194 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_182_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_200 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_idle : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_ready : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_ce0 : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_ce0 : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_ce0 : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_ce0 : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_ce1 : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_we1 : STD_LOGIC;
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sub_ln22_fu_72_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln22_1_fu_78_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln22_fu_88_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln22_2_fu_98_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_64_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln22_1_fu_92_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln22_1_fu_108_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln23_fu_128_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln23_1_fu_134_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln23_fu_144_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln23_2_fu_154_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_4_fu_120_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln23_1_fu_148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln23_1_fu_164_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_182_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_182_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal bound_fu_182_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_182_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component accel_top_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_width : IN STD_LOGIC_VECTOR (31 downto 0);
        bound : IN STD_LOGIC_VECTOR (63 downto 0);
        input_0_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_0_0_ce0 : OUT STD_LOGIC;
        input_0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_0_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_0_1_ce0 : OUT STD_LOGIC;
        input_0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_1_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_1_0_ce0 : OUT STD_LOGIC;
        input_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_1_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_1_1_ce0 : OUT STD_LOGIC;
        input_1_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        output_r_ce1 : OUT STD_LOGIC;
        output_r_we1 : OUT STD_LOGIC;
        output_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component accel_top_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48 : component accel_top_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start,
        ap_done => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done,
        ap_idle => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_idle,
        ap_ready => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_ready,
        out_width => out_width_reg_194,
        bound => bound_reg_200,
        input_0_0_address0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_address0,
        input_0_0_ce0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_ce0,
        input_0_0_q0 => input_0_0_q0,
        input_0_1_address0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_address0,
        input_0_1_ce0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_ce0,
        input_0_1_q0 => input_0_1_q0,
        input_1_0_address0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_address0,
        input_1_0_ce0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_ce0,
        input_1_0_q0 => input_1_0_q0,
        input_1_1_address0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_address0,
        input_1_1_ce0 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_ce0,
        input_1_1_q0 => input_1_1_q0,
        output_r_address1 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_address1,
        output_r_ce1 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_ce1,
        output_r_we1 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_we1,
        output_r_d1 => grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_d1);

    mul_32ns_32ns_64_1_1_U83 : component accel_top_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => bound_fu_182_p0,
        din1 => bound_fu_182_p1,
        dout => bound_fu_182_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_ready = ap_const_logic_1)) then 
                    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bound_reg_200 <= bound_fu_182_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                out_height_reg_189 <= out_height_fu_112_p3;
                out_width_reg_194 <= out_width_fu_168_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done)
    begin
        if ((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done, ap_CS_fsm_state3)
    begin
        if ((((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_fu_182_p0 <= bound_fu_182_p00(32 - 1 downto 0);
    bound_fu_182_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_height_reg_189),64));
    bound_fu_182_p1 <= bound_fu_182_p10(32 - 1 downto 0);
    bound_fu_182_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_width_reg_194),64));
    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg;
    input_0_0_address0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_address0;
    input_0_0_ce0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_ce0;
    input_0_1_address0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_address0;
    input_0_1_ce0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_ce0;
    input_1_0_address0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_address0;
    input_1_0_ce0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_ce0;
    input_1_1_address0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_address0;
    input_1_1_ce0 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_ce0;
    lshr_ln22_1_fu_78_p4 <= sub_ln22_fu_72_p2(31 downto 1);
    lshr_ln22_2_fu_98_p4 <= in_height(31 downto 1);
    lshr_ln23_1_fu_134_p4 <= sub_ln23_fu_128_p2(31 downto 1);
    lshr_ln23_2_fu_154_p4 <= in_width(31 downto 1);
    out_height_fu_112_p3 <= 
        sub_ln22_1_fu_92_p2 when (tmp_fu_64_p3(0) = '1') else 
        zext_ln22_1_fu_108_p1;
    out_width_fu_168_p3 <= 
        sub_ln23_1_fu_148_p2 when (tmp_4_fu_120_p3(0) = '1') else 
        zext_ln23_1_fu_164_p1;
    output_r_address1 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_address1;
    output_r_ce1 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_ce1;
    output_r_d1 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_d1;
    output_r_we1 <= grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_we1;
    sub_ln22_1_fu_92_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(zext_ln22_fu_88_p1));
    sub_ln22_fu_72_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(in_height));
    sub_ln23_1_fu_148_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(zext_ln23_fu_144_p1));
    sub_ln23_fu_128_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(in_width));
    tmp_4_fu_120_p3 <= in_width(31 downto 31);
    tmp_fu_64_p3 <= in_height(31 downto 31);
    zext_ln22_1_fu_108_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln22_2_fu_98_p4),32));
    zext_ln22_fu_88_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln22_1_fu_78_p4),32));
    zext_ln23_1_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln23_2_fu_154_p4),32));
    zext_ln23_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln23_1_fu_134_p4),32));
end behav;
