-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accel_top_relu is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    feature_map_0_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_0_0_ce0 : OUT STD_LOGIC;
    feature_map_0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_map_0_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_0_0_ce1 : OUT STD_LOGIC;
    feature_map_0_0_we1 : OUT STD_LOGIC;
    feature_map_0_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    feature_map_0_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_0_1_ce0 : OUT STD_LOGIC;
    feature_map_0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_map_0_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_0_1_ce1 : OUT STD_LOGIC;
    feature_map_0_1_we1 : OUT STD_LOGIC;
    feature_map_0_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    feature_map_1_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_1_0_ce0 : OUT STD_LOGIC;
    feature_map_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_map_1_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_1_0_ce1 : OUT STD_LOGIC;
    feature_map_1_0_we1 : OUT STD_LOGIC;
    feature_map_1_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    feature_map_1_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_1_1_ce0 : OUT STD_LOGIC;
    feature_map_1_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    feature_map_1_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    feature_map_1_1_ce1 : OUT STD_LOGIC;
    feature_map_1_1_we1 : OUT STD_LOGIC;
    feature_map_1_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of accel_top_relu is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bound_fu_59_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_71 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_idle : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_ready : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_ce0 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_ce1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_we1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_ce0 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_ce1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_we1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_ce0 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_ce1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_we1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_ce0 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_ce1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_we1 : STD_LOGIC;
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal bound_fu_59_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_59_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal bound_fu_59_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_59_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component accel_top_relu_Pipeline_RELU_ROW_RELU_COL IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bound : IN STD_LOGIC_VECTOR (63 downto 0);
        width : IN STD_LOGIC_VECTOR (31 downto 0);
        feature_map_1_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_1_1_ce0 : OUT STD_LOGIC;
        feature_map_1_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        feature_map_1_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_1_1_ce1 : OUT STD_LOGIC;
        feature_map_1_1_we1 : OUT STD_LOGIC;
        feature_map_1_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        feature_map_1_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_1_0_ce0 : OUT STD_LOGIC;
        feature_map_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        feature_map_1_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_1_0_ce1 : OUT STD_LOGIC;
        feature_map_1_0_we1 : OUT STD_LOGIC;
        feature_map_1_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        feature_map_0_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_0_1_ce0 : OUT STD_LOGIC;
        feature_map_0_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        feature_map_0_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_0_1_ce1 : OUT STD_LOGIC;
        feature_map_0_1_we1 : OUT STD_LOGIC;
        feature_map_0_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        feature_map_0_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_0_0_ce0 : OUT STD_LOGIC;
        feature_map_0_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        feature_map_0_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        feature_map_0_0_ce1 : OUT STD_LOGIC;
        feature_map_0_0_we1 : OUT STD_LOGIC;
        feature_map_0_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component accel_top_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36 : component accel_top_relu_Pipeline_RELU_ROW_RELU_COL
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start,
        ap_done => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done,
        ap_idle => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_idle,
        ap_ready => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_ready,
        bound => bound_reg_71,
        width => width,
        feature_map_1_1_address0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_address0,
        feature_map_1_1_ce0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_ce0,
        feature_map_1_1_q0 => feature_map_1_1_q0,
        feature_map_1_1_address1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_address1,
        feature_map_1_1_ce1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_ce1,
        feature_map_1_1_we1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_we1,
        feature_map_1_1_d1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_d1,
        feature_map_1_0_address0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_address0,
        feature_map_1_0_ce0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_ce0,
        feature_map_1_0_q0 => feature_map_1_0_q0,
        feature_map_1_0_address1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_address1,
        feature_map_1_0_ce1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_ce1,
        feature_map_1_0_we1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_we1,
        feature_map_1_0_d1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_d1,
        feature_map_0_1_address0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_address0,
        feature_map_0_1_ce0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_ce0,
        feature_map_0_1_q0 => feature_map_0_1_q0,
        feature_map_0_1_address1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_address1,
        feature_map_0_1_ce1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_ce1,
        feature_map_0_1_we1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_we1,
        feature_map_0_1_d1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_d1,
        feature_map_0_0_address0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_address0,
        feature_map_0_0_ce0 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_ce0,
        feature_map_0_0_q0 => feature_map_0_0_q0,
        feature_map_0_0_address1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_address1,
        feature_map_0_0_ce1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_ce1,
        feature_map_0_0_we1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_we1,
        feature_map_0_0_d1 => grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_d1);

    mul_32ns_32ns_64_1_1_U69 : component accel_top_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => bound_fu_59_p0,
        din1 => bound_fu_59_p1,
        dout => bound_fu_59_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_ready = ap_const_logic_1)) then 
                    grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                bound_reg_71 <= bound_fu_59_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done)
    begin
        if ((grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_fu_59_p0 <= bound_fu_59_p00(32 - 1 downto 0);
    bound_fu_59_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),64));
    bound_fu_59_p1 <= bound_fu_59_p10(32 - 1 downto 0);
    bound_fu_59_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),64));
    feature_map_0_0_address0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_address0;
    feature_map_0_0_address1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_address1;
    feature_map_0_0_ce0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_ce0;
    feature_map_0_0_ce1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_ce1;
    feature_map_0_0_d1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_d1;
    feature_map_0_0_we1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_0_we1;
    feature_map_0_1_address0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_address0;
    feature_map_0_1_address1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_address1;
    feature_map_0_1_ce0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_ce0;
    feature_map_0_1_ce1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_ce1;
    feature_map_0_1_d1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_d1;
    feature_map_0_1_we1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_0_1_we1;
    feature_map_1_0_address0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_address0;
    feature_map_1_0_address1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_address1;
    feature_map_1_0_ce0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_ce0;
    feature_map_1_0_ce1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_ce1;
    feature_map_1_0_d1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_d1;
    feature_map_1_0_we1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_0_we1;
    feature_map_1_1_address0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_address0;
    feature_map_1_1_address1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_address1;
    feature_map_1_1_ce0 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_ce0;
    feature_map_1_1_ce1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_ce1;
    feature_map_1_1_d1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_d1;
    feature_map_1_1_we1 <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_feature_map_1_1_we1;
    grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start <= grp_relu_Pipeline_RELU_ROW_RELU_COL_fu_36_ap_start_reg;
end behav;
