/**
 * =============================================================================
 * File: cnn_driver.h
 * Description: Software driver for the CNN Accelerator HLS IP.
 *              Provides simple C functions to configure and run the
 *              accelerator from the ARM Cortex-A9 processor.
 *
 *              These functions write to the AXI-Lite registers that
 *              Vitis HLS auto-generated from the #pragma HLS INTERFACE
 *              directives in accel_top.cpp.
 *
 *              Similar to how you called your RISC-V core IPs from
 *              the ARM PS in your multicore project.
 *
 * Author: Molik Rajvanshi
 * Project: Edge AI Inference SoC with Hardware Root-of-Trust
 * =============================================================================
 */

#ifndef CNN_DRIVER_H
#define CNN_DRIVER_H

#include <stdint.h>

// =============================================================================
// Base addresses (set in Vivado Block Design — Address Editor)
// These get assigned when you connect the IP in the block design
// =============================================================================
#define CNN_ACCEL_BASE_ADDR    0x43C00000   // Typical GP0 address for first IP

// =============================================================================
// AXI-Lite Register Offsets (auto-generated by Vitis HLS)
// You can find these in the exported IP's driver header:
//   solution1/impl/ip/drivers/accel_top_v1_0/src/xaccel_top_hw.h
//
// These are the s_axilite registers for each function parameter:
// =============================================================================
#define CNN_REG_CTRL          0x00   // Control: [0] ap_start, [1] ap_done, [2] ap_idle
#define CNN_REG_GIE           0x04   // Global Interrupt Enable
#define CNN_REG_IER           0x08   // IP Interrupt Enable Register
#define CNN_REG_ISR           0x0C   // IP Interrupt Status Register

// Data pointers (m_axi offset registers)
#define CNN_REG_INPUT_DATA    0x10   // Base address of input data in DDR
#define CNN_REG_WEIGHT_DATA   0x18   // Base address of weight data in DDR
#define CNN_REG_BIAS_DATA     0x20   // Base address of bias data in DDR
#define CNN_REG_OUTPUT_DATA   0x28   // Base address of output data in DDR

// Layer configuration registers
#define CNN_REG_KERNEL_SIZE   0x30
#define CNN_REG_IN_CHANNELS   0x38
#define CNN_REG_OUT_CHANNELS  0x40
#define CNN_REG_IN_HEIGHT     0x48
#define CNN_REG_IN_WIDTH      0x50
#define CNN_REG_STRIDE        0x58
#define CNN_REG_PADDING       0x60
#define CNN_REG_RELU_ENABLE   0x68
#define CNN_REG_POOL_ENABLE   0x70

// =============================================================================
// Control register bits
// =============================================================================
#define CNN_CTRL_AP_START     0x01
#define CNN_CTRL_AP_DONE      0x02
#define CNN_CTRL_AP_IDLE      0x04

// =============================================================================
// Memory-mapped I/O helper macros
// (same approach as Xilinx xil_io.h)
// =============================================================================
#define MMIO_WRITE(addr, val)  (*(volatile uint32_t *)(addr) = (val))
#define MMIO_READ(addr)        (*(volatile uint32_t *)(addr))

// =============================================================================
// Driver Functions
// =============================================================================

/**
 * cnn_init() — Initialize the CNN accelerator IP.
 */
static inline void cnn_init(uint32_t base_addr) {
    // Nothing special needed — just ensure IP is idle
    (void)base_addr;
}

/**
 * cnn_is_idle() — Check if accelerator is idle (ready for new task).
 */
static inline int cnn_is_idle(uint32_t base_addr) {
    uint32_t ctrl = MMIO_READ(base_addr + CNN_REG_CTRL);
    return (ctrl & CNN_CTRL_AP_IDLE) != 0;
}

/**
 * cnn_is_done() — Check if accelerator has completed.
 */
static inline int cnn_is_done(uint32_t base_addr) {
    uint32_t ctrl = MMIO_READ(base_addr + CNN_REG_CTRL);
    return (ctrl & CNN_CTRL_AP_DONE) != 0;
}

/**
 * cnn_configure() — Set layer parameters before starting inference.
 */
static inline void cnn_configure(
    uint32_t base_addr,
    uint32_t input_addr,     // DDR address of input data
    uint32_t weight_addr,    // DDR address of weights
    uint32_t bias_addr,      // DDR address of bias
    uint32_t output_addr,    // DDR address for output
    int      kernel_size,
    int      in_channels,
    int      out_channels,
    int      in_height,
    int      in_width,
    int      stride,
    int      padding,
    int      relu_enable,
    int      pool_enable
) {
    // Set data pointers
    MMIO_WRITE(base_addr + CNN_REG_INPUT_DATA,  input_addr);
    MMIO_WRITE(base_addr + CNN_REG_WEIGHT_DATA, weight_addr);
    MMIO_WRITE(base_addr + CNN_REG_BIAS_DATA,   bias_addr);
    MMIO_WRITE(base_addr + CNN_REG_OUTPUT_DATA, output_addr);

    // Set layer configuration
    MMIO_WRITE(base_addr + CNN_REG_KERNEL_SIZE,  kernel_size);
    MMIO_WRITE(base_addr + CNN_REG_IN_CHANNELS,  in_channels);
    MMIO_WRITE(base_addr + CNN_REG_OUT_CHANNELS, out_channels);
    MMIO_WRITE(base_addr + CNN_REG_IN_HEIGHT,    in_height);
    MMIO_WRITE(base_addr + CNN_REG_IN_WIDTH,     in_width);
    MMIO_WRITE(base_addr + CNN_REG_STRIDE,       stride);
    MMIO_WRITE(base_addr + CNN_REG_PADDING,      padding);
    MMIO_WRITE(base_addr + CNN_REG_RELU_ENABLE,  relu_enable);
    MMIO_WRITE(base_addr + CNN_REG_POOL_ENABLE,  pool_enable);
}

/**
 * cnn_start() — Trigger accelerator execution.
 */
static inline void cnn_start(uint32_t base_addr) {
    MMIO_WRITE(base_addr + CNN_REG_CTRL, CNN_CTRL_AP_START);
}

/**
 * cnn_wait_done() — Block until accelerator completes.
 */
static inline void cnn_wait_done(uint32_t base_addr) {
    while (!cnn_is_done(base_addr)) {
        // Busy wait (could use interrupt instead)
    }
}

#endif // CNN_DRIVER_H
