-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accel_top_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bias : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln36_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln36_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bound4 : IN STD_LOGIC_VECTOR (95 downto 0);
    bound : IN STD_LOGIC_VECTOR (63 downto 0);
    and_ln52_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    kernel_size : IN STD_LOGIC_VECTOR (31 downto 0);
    icmp_ln48_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    weights_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    weights_ce0 : OUT STD_LOGIC;
    weights_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln43 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36 : IN STD_LOGIC_VECTOR (31 downto 0);
    sum_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_V_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of accel_top_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv96_1 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln43_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln36_cast_fu_205_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln36_cast_reg_755 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln43_cast_fu_209_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln43_cast_reg_760 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln36_1_cast_fu_213_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln36_1_cast_reg_765 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln36_2_cast_fu_217_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln36_2_cast_reg_771 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln43_reg_777 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_777_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_777_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_777_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_777_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_reg_781 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_reg_781_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_reg_791 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_3_fu_403_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_3_reg_796 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_fu_420_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln44_reg_801 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln44_reg_801_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln55_fu_446_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln55_reg_807 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln55_1_fu_450_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln55_1_reg_812 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln45_1_fu_458_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln45_1_reg_817 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln54_fu_489_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln54_reg_822 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln46_1_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_1_reg_827 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_2_fu_500_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln55_2_reg_832 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln44_3_fu_567_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_3_reg_837 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln55_2_fu_579_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln54_1_fu_598_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum_V_1_fu_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_668_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_sum_V_1_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal kw_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln48_fu_504_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal kh_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln44_1_fu_428_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_fu_100 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln44_4_fu_279_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ic_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_1_fu_353_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten27_fu_108 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln43_1_fu_259_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal sext_ln43_cast_fu_209_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_2_cast_fu_217_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_1_fu_273_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_fu_300_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln45_fu_304_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_fu_309_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln43_fu_340_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln54_fu_364_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_376_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal zext_ln55_fu_384_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln54_fu_360_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal sub_ln55_fu_388_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal icmp_ln48_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_fu_346_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln44_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln44_fu_409_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln43_1_fu_394_p1 : STD_LOGIC_VECTOR (36 downto 0);
    signal zext_ln55_1_fu_436_p1 : STD_LOGIC_VECTOR (36 downto 0);
    signal add_ln55_fu_440_p2 : STD_LOGIC_VECTOR (36 downto 0);
    signal zext_ln44_1_fu_454_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln54_2_fu_467_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln54_2_fu_467_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln54_3_fu_470_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln54_1_fu_463_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln43_4_fu_474_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_cast_fu_368_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln44_2_fu_481_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl_fu_530_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_5_fu_549_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_1_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_4_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_2_fu_525_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln55_1_fu_537_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln55_1_fu_574_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_1_fu_584_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln51_1_fu_584_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_542_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln54_4_fu_588_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln54_1_fu_592_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln48_fu_603_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln51_fu_606_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_7_fu_611_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_1_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_2_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_val_V_2_fu_641_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component accel_top_mac_muladd_8s_8s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component accel_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8s_8s_32s_32_4_1_U20 : component accel_top_mac_muladd_8s_8s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_q0,
        din1 => in_val_V_2_fu_641_p3,
        din2 => ap_sig_allocacmp_sum_V_1_load,
        ce => ap_const_logic_1,
        dout => grp_fu_668_p3);

    flow_control_loop_pipe_sequential_init_U : component accel_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ic_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ic_fu_104 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_777 = ap_const_lv1_0))) then 
                    ic_fu_104 <= select_ln43_1_fu_353_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten27_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten27_fu_108 <= ap_const_lv96_0;
                elsif (((icmp_ln43_fu_254_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten27_fu_108 <= add_ln43_1_fu_259_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_100 <= ap_const_lv64_0;
                elsif (((icmp_ln43_fu_254_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_100 <= select_ln44_4_fu_279_p3;
                end if;
            end if; 
        end if;
    end process;

    kh_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    kh_fu_96 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_777 = ap_const_lv1_0))) then 
                    kh_fu_96 <= select_ln44_1_fu_428_p3;
                end if;
            end if; 
        end if;
    end process;

    kw_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    kw_fu_92 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_777 = ap_const_lv1_0))) then 
                    kw_fu_92 <= add_ln48_fu_504_p2;
                end if;
            end if; 
        end if;
    end process;

    sum_V_1_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    sum_V_1_fu_88 <= bias;
                elsif ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then 
                    sum_V_1_fu_88 <= grp_fu_668_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln43_reg_777 = ap_const_lv1_0))) then
                add_ln45_1_reg_817 <= add_ln45_1_fu_458_p2;
                add_ln54_reg_822 <= add_ln54_fu_489_p2;
                icmp_ln46_1_reg_827 <= icmp_ln46_1_fu_495_p2;
                select_ln43_3_reg_796 <= select_ln43_3_fu_403_p3;
                select_ln44_reg_801 <= select_ln44_fu_420_p3;
                trunc_ln55_1_reg_812 <= trunc_ln55_1_fu_450_p1;
                trunc_ln55_2_reg_832 <= trunc_ln55_2_fu_500_p1;
                trunc_ln55_reg_807 <= trunc_ln55_fu_446_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln44_reg_781 = ap_const_lv1_0))) then
                and_ln52_reg_791 <= and_ln52_fu_328_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln43_reg_777 <= icmp_ln43_fu_254_p2;
                sext_ln36_1_cast_reg_765 <= sext_ln36_1_cast_fu_213_p1;
                sext_ln36_2_cast_reg_771 <= sext_ln36_2_cast_fu_217_p1;
                sext_ln36_cast_reg_755 <= sext_ln36_cast_fu_205_p1;
                sext_ln43_cast_reg_760 <= sext_ln43_cast_fu_209_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln43_reg_777_pp0_iter2_reg <= icmp_ln43_reg_777;
                icmp_ln43_reg_777_pp0_iter3_reg <= icmp_ln43_reg_777_pp0_iter2_reg;
                icmp_ln43_reg_777_pp0_iter4_reg <= icmp_ln43_reg_777_pp0_iter3_reg;
                icmp_ln43_reg_777_pp0_iter5_reg <= icmp_ln43_reg_777_pp0_iter4_reg;
                icmp_ln44_reg_781_pp0_iter2_reg <= icmp_ln44_reg_781;
                select_ln44_3_reg_837 <= select_ln44_3_fu_567_p3;
                select_ln44_reg_801_pp0_iter3_reg <= select_ln44_reg_801;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln43_fu_254_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln44_reg_781 <= icmp_ln44_fu_268_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln43_1_fu_259_p2 <= std_logic_vector(unsigned(indvar_flatten27_fu_108) + unsigned(ap_const_lv96_1));
    add_ln43_fu_340_p2 <= std_logic_vector(unsigned(ic_fu_104) + unsigned(ap_const_lv32_1));
    add_ln44_1_fu_273_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_100) + unsigned(ap_const_lv64_1));
    add_ln44_fu_409_p2 <= std_logic_vector(unsigned(select_ln43_fu_346_p3) + unsigned(ap_const_lv32_1));
    add_ln45_1_fu_458_p2 <= std_logic_vector(unsigned(zext_ln44_1_fu_454_p1) + unsigned(sext_ln36_2_cast_reg_771));
    add_ln45_fu_304_p2 <= std_logic_vector(unsigned(zext_ln44_fu_300_p1) + unsigned(sext_ln36_2_cast_reg_771));
    add_ln48_fu_504_p2 <= std_logic_vector(unsigned(select_ln44_fu_420_p3) + unsigned(ap_const_lv32_1));
    add_ln51_1_fu_584_p1 <= sext_ln43;
    add_ln51_1_fu_584_p2 <= std_logic_vector(unsigned(select_ln44_reg_801) + unsigned(add_ln51_1_fu_584_p1));
    add_ln51_fu_606_p2 <= std_logic_vector(unsigned(zext_ln48_fu_603_p1) + unsigned(sext_ln43_cast_reg_760));
    add_ln54_1_fu_592_p2 <= std_logic_vector(unsigned(tmp_9_fu_542_p3) + unsigned(trunc_ln54_4_fu_588_p1));
    add_ln54_fu_489_p2 <= std_logic_vector(unsigned(tmp_5_cast_fu_368_p3) + unsigned(select_ln44_2_fu_481_p3));
    add_ln55_1_fu_574_p2 <= std_logic_vector(unsigned(sub_ln55_1_fu_537_p2) + unsigned(trunc_ln55_2_reg_832));
    add_ln55_fu_440_p2 <= std_logic_vector(signed(sext_ln43_1_fu_394_p1) + signed(zext_ln55_1_fu_436_p1));
    and_ln52_1_fu_630_p2 <= (xor_ln52_fu_619_p2 and icmp_ln52_fu_625_p2);
    and_ln52_2_fu_636_p2 <= (select_ln44_3_reg_837 and and_ln52_1_fu_630_p2);
    and_ln52_4_fu_562_p2 <= (xor_ln46_1_fu_556_p2 and icmp_ln46_1_reg_827);
    and_ln52_fu_328_p2 <= (xor_ln46_fu_317_p2 and icmp_ln46_fu_323_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln43_fu_254_p2)
    begin
        if (((icmp_ln43_fu_254_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln43_reg_777)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_777 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_sum_V_1_load_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0, sum_V_1_fu_88, grp_fu_668_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            ap_sig_allocacmp_sum_V_1_load <= grp_fu_668_p3;
        else 
            ap_sig_allocacmp_sum_V_1_load <= sum_V_1_fu_88;
        end if; 
    end process;

    icmp_ln43_fu_254_p2 <= "1" when (indvar_flatten27_fu_108 = bound4) else "0";
    icmp_ln44_fu_268_p2 <= "1" when (indvar_flatten_fu_100 = bound) else "0";
    icmp_ln46_1_fu_495_p2 <= "1" when (signed(add_ln45_1_fu_458_p2) < signed(sext_ln36_1_cast_reg_765)) else "0";
    icmp_ln46_fu_323_p2 <= "1" when (signed(add_ln45_fu_304_p2) < signed(sext_ln36_1_cast_reg_765)) else "0";
    icmp_ln48_fu_398_p2 <= "1" when (kw_fu_92 = kernel_size) else "0";
    icmp_ln52_fu_625_p2 <= "1" when (signed(add_ln51_fu_606_p2) < signed(sext_ln36_cast_reg_755)) else "0";
    in_val_V_2_fu_641_p3 <= 
        input_r_q0 when (and_ln52_2_fu_636_p2(0) = '1') else 
        ap_const_lv8_0;
    input_r_address0 <= zext_ln54_1_fu_598_p1(16 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln44_fu_415_p2 <= (select_ln43_3_fu_403_p3 or icmp_ln44_reg_781);
    p_shl_fu_530_p3 <= (trunc_ln55_1_reg_812 & ap_const_lv3_0);
    select_ln43_1_fu_353_p3 <= 
        add_ln43_fu_340_p2 when (icmp_ln44_reg_781(0) = '1') else 
        ic_fu_104;
    select_ln43_2_fu_525_p3 <= 
        and_ln52_3 when (icmp_ln44_reg_781_pp0_iter2_reg(0) = '1') else 
        and_ln52_reg_791;
    select_ln43_3_fu_403_p3 <= 
        icmp_ln48_1 when (icmp_ln44_reg_781(0) = '1') else 
        icmp_ln48_fu_398_p2;
    select_ln43_4_fu_474_p3 <= 
        trunc_ln54_2_fu_467_p1 when (icmp_ln44_reg_781(0) = '1') else 
        trunc_ln54_3_fu_470_p1;
    select_ln43_fu_346_p3 <= 
        ap_const_lv32_0 when (icmp_ln44_reg_781(0) = '1') else 
        kh_fu_96;
    select_ln44_1_fu_428_p3 <= 
        add_ln44_fu_409_p2 when (select_ln43_3_fu_403_p3(0) = '1') else 
        select_ln43_fu_346_p3;
    select_ln44_2_fu_481_p3 <= 
        trunc_ln54_1_fu_463_p1 when (select_ln43_3_fu_403_p3(0) = '1') else 
        select_ln43_4_fu_474_p3;
    select_ln44_3_fu_567_p3 <= 
        and_ln52_4_fu_562_p2 when (select_ln43_3_reg_796(0) = '1') else 
        select_ln43_2_fu_525_p3;
    select_ln44_4_fu_279_p3 <= 
        ap_const_lv64_1 when (icmp_ln44_fu_268_p2(0) = '1') else 
        add_ln44_1_fu_273_p2;
    select_ln44_fu_420_p3 <= 
        ap_const_lv32_0 when (or_ln44_fu_415_p2(0) = '1') else 
        kw_fu_92;
        sext_ln36_1_cast_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_1),34));

    sext_ln36_2_cast_fu_217_p0 <= sext_ln36_2;
        sext_ln36_2_cast_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_2_cast_fu_217_p0),34));

        sext_ln36_cast_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36),34));

        sext_ln43_1_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln55_fu_388_p2),37));

    sext_ln43_cast_fu_209_p0 <= sext_ln43;
        sext_ln43_cast_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln43_cast_fu_209_p0),34));

    sub_ln55_1_fu_537_p2 <= std_logic_vector(unsigned(p_shl_fu_530_p3) - unsigned(trunc_ln55_reg_807));
    sub_ln55_fu_388_p2 <= std_logic_vector(unsigned(zext_ln55_fu_384_p1) - unsigned(zext_ln54_fu_360_p1));
    sum_V_1_out <= sum_V_1_fu_88;

    sum_V_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln43_reg_777_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln43_reg_777_pp0_iter5_reg = ap_const_lv1_1))) then 
            sum_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            sum_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_5_cast_fu_368_p3 <= (trunc_ln54_fu_364_p1 & ap_const_lv5_0);
    tmp_5_fu_549_p3 <= add_ln45_1_reg_817(33 downto 33);
    tmp_6_fu_376_p3 <= (select_ln43_1_fu_353_p3 & ap_const_lv3_0);
    tmp_7_fu_611_p3 <= add_ln51_fu_606_p2(33 downto 33);
    tmp_9_fu_542_p3 <= (add_ln54_reg_822 & ap_const_lv5_0);
    tmp_fu_309_p3 <= add_ln45_fu_304_p2(33 downto 33);
    trunc_ln54_1_fu_463_p1 <= add_ln45_1_fu_458_p2(11 - 1 downto 0);
    trunc_ln54_2_fu_467_p0 <= sext_ln36_2;
    trunc_ln54_2_fu_467_p1 <= trunc_ln54_2_fu_467_p0(11 - 1 downto 0);
    trunc_ln54_3_fu_470_p1 <= add_ln45_fu_304_p2(11 - 1 downto 0);
    trunc_ln54_4_fu_588_p1 <= add_ln51_1_fu_584_p2(16 - 1 downto 0);
    trunc_ln54_fu_364_p1 <= select_ln43_1_fu_353_p3(6 - 1 downto 0);
    trunc_ln55_1_fu_450_p1 <= add_ln55_fu_440_p2(9 - 1 downto 0);
    trunc_ln55_2_fu_500_p1 <= select_ln44_fu_420_p3(12 - 1 downto 0);
    trunc_ln55_fu_446_p1 <= add_ln55_fu_440_p2(12 - 1 downto 0);
    weights_address0 <= zext_ln55_2_fu_579_p1(12 - 1 downto 0);

    weights_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            weights_ce0 <= ap_const_logic_1;
        else 
            weights_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln46_1_fu_556_p2 <= (tmp_5_fu_549_p3 xor ap_const_lv1_1);
    xor_ln46_fu_317_p2 <= (tmp_fu_309_p3 xor ap_const_lv1_1);
    xor_ln52_fu_619_p2 <= (tmp_7_fu_611_p3 xor ap_const_lv1_1);
    zext_ln44_1_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln44_fu_409_p2),34));
    zext_ln44_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kh_fu_96),34));
    zext_ln48_fu_603_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln44_reg_801_pp0_iter3_reg),34));
    zext_ln54_1_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln54_1_fu_592_p2),64));
    zext_ln54_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_1_fu_353_p3),36));
    zext_ln55_1_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln44_1_fu_428_p3),37));
    zext_ln55_2_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln55_1_fu_574_p2),64));
    zext_ln55_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_376_p3),36));
end behav;
