-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accel_top_accel_top_Pipeline_STORE_W is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_DATA_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_AWREADY : IN STD_LOGIC;
    m_axi_DATA_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_DATA_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_WVALID : OUT STD_LOGIC;
    m_axi_DATA_WREADY : IN STD_LOGIC;
    m_axi_DATA_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_WLAST : OUT STD_LOGIC;
    m_axi_DATA_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_ARREADY : IN STD_LOGIC;
    m_axi_DATA_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_DATA_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RVALID : IN STD_LOGIC;
    m_axi_DATA_RREADY : OUT STD_LOGIC;
    m_axi_DATA_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_RLAST : IN STD_LOGIC;
    m_axi_DATA_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_DATA_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_BVALID : IN STD_LOGIC;
    m_axi_DATA_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln166_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    final_width : IN STD_LOGIC_VECTOR (30 downto 0);
    zext_ln164 : IN STD_LOGIC_VECTOR (9 downto 0);
    pool_output_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pool_output_V_ce0 : OUT STD_LOGIC;
    pool_output_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_data : IN STD_LOGIC_VECTOR (63 downto 0);
    zext_ln166_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    conv_output_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_output_V_ce0 : OUT STD_LOGIC;
    conv_output_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_output_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_output_V_1_ce0 : OUT STD_LOGIC;
    conv_output_V_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_output_V_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_output_V_2_ce0 : OUT STD_LOGIC;
    conv_output_V_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_output_V_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    conv_output_V_3_ce0 : OUT STD_LOGIC;
    conv_output_V_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    trunc_ln160_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln104 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of accel_top_accel_top_Pipeline_STORE_W is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv33_1 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln161_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal DATA_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal DATA_blk_n_W : STD_LOGIC;
    signal DATA_blk_n_B : STD_LOGIC;
    signal icmp_ln104_read_reg_414 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln161_fu_286_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln161_reg_453 : STD_LOGIC_VECTOR (0 downto 0);
    signal DATA_addr_reg_459 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln104_fu_393_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln104_reg_485 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln164_1_fu_281_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln166_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln166_fu_323_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal w_fu_110 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln161_fu_263_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal out_ptr_fu_114 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln166_fu_290_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln166_1_cast_fu_241_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln164_fu_272_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln164_fu_276_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln4_fu_296_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln166_2_fu_304_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln166_1_fu_308_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln8_fu_313_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal lshr_ln166_1_fu_333_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln166_2_fu_343_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_366_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_375_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_384_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component accel_top_mux_21_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component accel_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_21_32_1_1_U91 : component accel_top_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => conv_output_V_q0,
        din1 => conv_output_V_1_q0,
        din2 => trunc_ln161_reg_453,
        dout => tmp_fu_366_p4);

    mux_21_32_1_1_U92 : component accel_top_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => conv_output_V_2_q0,
        din1 => conv_output_V_3_q0,
        din2 => trunc_ln161_reg_453,
        dout => tmp_s_fu_375_p4);

    mux_21_32_1_1_U93 : component accel_top_mux_21_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 1,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_fu_366_p4,
        din1 => tmp_s_fu_375_p4,
        din2 => trunc_ln160_1,
        dout => tmp_1_fu_384_p4);

    flow_control_loop_pipe_sequential_init_U : component accel_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    out_ptr_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    out_ptr_fu_114 <= sext_ln166_1_cast_fu_241_p1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln161_fu_258_p2 = ap_const_lv1_0))) then 
                    out_ptr_fu_114 <= add_ln166_fu_290_p2;
                end if;
            end if; 
        end if;
    end process;

    w_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_110 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln161_fu_258_p2 = ap_const_lv1_0))) then 
                    w_fu_110 <= add_ln161_fu_263_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln161_fu_258_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                DATA_addr_reg_459 <= sext_ln166_fu_323_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                select_ln104_reg_485 <= select_ln104_fu_393_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln104_read_reg_414 = ap_const_lv1_0) and (icmp_ln161_fu_258_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln161_reg_453 <= trunc_ln161_fu_286_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    DATA_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_DATA_AWREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            DATA_blk_n_AW <= m_axi_DATA_AWREADY;
        else 
            DATA_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    DATA_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_DATA_BVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            DATA_blk_n_B <= m_axi_DATA_BVALID;
        else 
            DATA_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    DATA_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_DATA_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            DATA_blk_n_W <= m_axi_DATA_WREADY;
        else 
            DATA_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    add_ln161_fu_263_p2 <= std_logic_vector(unsigned(w_fu_110) + unsigned(ap_const_lv31_1));
    add_ln164_fu_276_p2 <= std_logic_vector(unsigned(zext_ln164) + unsigned(trunc_ln164_fu_272_p1));
    add_ln166_1_fu_308_p2 <= std_logic_vector(signed(sext_ln166_2_fu_304_p1) + signed(output_data));
    add_ln166_2_fu_343_p2 <= std_logic_vector(unsigned(zext_ln166_1) + unsigned(lshr_ln166_1_fu_333_p4));
    add_ln166_fu_290_p2 <= std_logic_vector(unsigned(out_ptr_fu_114) + unsigned(ap_const_lv33_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_DATA_BVALID)
    begin
                ap_block_pp0_stage0_01001 <= ((m_axi_DATA_BVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, m_axi_DATA_AWREADY, m_axi_DATA_WREADY, m_axi_DATA_BVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_DATA_BVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1)) or ((m_axi_DATA_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((m_axi_DATA_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, m_axi_DATA_AWREADY, m_axi_DATA_WREADY, m_axi_DATA_BVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_DATA_BVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1)) or ((m_axi_DATA_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((m_axi_DATA_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter8_assign_proc : process(m_axi_DATA_BVALID)
    begin
                ap_block_state9_pp0_stage0_iter8 <= (m_axi_DATA_BVALID = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln161_fu_258_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln161_fu_258_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    conv_output_V_1_address0 <= zext_ln166_fu_348_p1(8 - 1 downto 0);

    conv_output_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conv_output_V_1_ce0 <= ap_const_logic_1;
        else 
            conv_output_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    conv_output_V_2_address0 <= zext_ln166_fu_348_p1(8 - 1 downto 0);

    conv_output_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conv_output_V_2_ce0 <= ap_const_logic_1;
        else 
            conv_output_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    conv_output_V_3_address0 <= zext_ln166_fu_348_p1(8 - 1 downto 0);

    conv_output_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conv_output_V_3_ce0 <= ap_const_logic_1;
        else 
            conv_output_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    conv_output_V_address0 <= zext_ln166_fu_348_p1(8 - 1 downto 0);

    conv_output_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            conv_output_V_ce0 <= ap_const_logic_1;
        else 
            conv_output_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln104_read_reg_414 <= icmp_ln104;
    icmp_ln161_fu_258_p2 <= "1" when (w_fu_110 = final_width) else "0";
    lshr_ln166_1_fu_333_p4 <= w_fu_110(8 downto 1);
    m_axi_DATA_ARADDR <= ap_const_lv64_0;
    m_axi_DATA_ARBURST <= ap_const_lv2_0;
    m_axi_DATA_ARCACHE <= ap_const_lv4_0;
    m_axi_DATA_ARID <= ap_const_lv1_0;
    m_axi_DATA_ARLEN <= ap_const_lv32_0;
    m_axi_DATA_ARLOCK <= ap_const_lv2_0;
    m_axi_DATA_ARPROT <= ap_const_lv3_0;
    m_axi_DATA_ARQOS <= ap_const_lv4_0;
    m_axi_DATA_ARREGION <= ap_const_lv4_0;
    m_axi_DATA_ARSIZE <= ap_const_lv3_0;
    m_axi_DATA_ARUSER <= ap_const_lv1_0;
    m_axi_DATA_ARVALID <= ap_const_logic_0;
    m_axi_DATA_AWADDR <= DATA_addr_reg_459;
    m_axi_DATA_AWBURST <= ap_const_lv2_0;
    m_axi_DATA_AWCACHE <= ap_const_lv4_0;
    m_axi_DATA_AWID <= ap_const_lv1_0;
    m_axi_DATA_AWLEN <= ap_const_lv32_1;
    m_axi_DATA_AWLOCK <= ap_const_lv2_0;
    m_axi_DATA_AWPROT <= ap_const_lv3_0;
    m_axi_DATA_AWQOS <= ap_const_lv4_0;
    m_axi_DATA_AWREGION <= ap_const_lv4_0;
    m_axi_DATA_AWSIZE <= ap_const_lv3_0;
    m_axi_DATA_AWUSER <= ap_const_lv1_0;

    m_axi_DATA_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_DATA_AWVALID <= ap_const_logic_1;
        else 
            m_axi_DATA_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_DATA_BREADY_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_DATA_BREADY <= ap_const_logic_1;
        else 
            m_axi_DATA_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_DATA_RREADY <= ap_const_logic_0;
    m_axi_DATA_WDATA <= select_ln104_reg_485;
    m_axi_DATA_WID <= ap_const_lv1_0;
    m_axi_DATA_WLAST <= ap_const_logic_0;
    m_axi_DATA_WSTRB <= ap_const_lv4_F;
    m_axi_DATA_WUSER <= ap_const_lv1_0;

    m_axi_DATA_WVALID_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_DATA_WVALID <= ap_const_logic_1;
        else 
            m_axi_DATA_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    pool_output_V_address0 <= zext_ln164_1_fu_281_p1(10 - 1 downto 0);

    pool_output_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            pool_output_V_ce0 <= ap_const_logic_1;
        else 
            pool_output_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln104_fu_393_p3 <= 
        pool_output_V_q0 when (icmp_ln104(0) = '1') else 
        tmp_1_fu_384_p4;
        sext_ln166_1_cast_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln166_1),33));

        sext_ln166_2_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln4_fu_296_p3),64));

        sext_ln166_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln8_fu_313_p4),64));

    shl_ln4_fu_296_p3 <= (out_ptr_fu_114 & ap_const_lv2_0);
    trunc_ln161_fu_286_p1 <= w_fu_110(1 - 1 downto 0);
    trunc_ln164_fu_272_p1 <= w_fu_110(10 - 1 downto 0);
    trunc_ln8_fu_313_p4 <= add_ln166_1_fu_308_p2(63 downto 2);
    zext_ln164_1_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln164_fu_276_p2),64));
    zext_ln166_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln166_2_fu_343_p2),64));
end behav;
