// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="aes128_top_aes128_top,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=90,HLS_SYN_TPT=none,HLS_SYN_MEM=15,HLS_SYN_DSP=0,HLS_SYN_FF=3480,HLS_SYN_LUT=26108,HLS_VERSION=2022_1}" *)

module aes128_top (
        ap_clk,
        ap_rst_n,
        m_axi_DATA_AWVALID,
        m_axi_DATA_AWREADY,
        m_axi_DATA_AWADDR,
        m_axi_DATA_AWID,
        m_axi_DATA_AWLEN,
        m_axi_DATA_AWSIZE,
        m_axi_DATA_AWBURST,
        m_axi_DATA_AWLOCK,
        m_axi_DATA_AWCACHE,
        m_axi_DATA_AWPROT,
        m_axi_DATA_AWQOS,
        m_axi_DATA_AWREGION,
        m_axi_DATA_AWUSER,
        m_axi_DATA_WVALID,
        m_axi_DATA_WREADY,
        m_axi_DATA_WDATA,
        m_axi_DATA_WSTRB,
        m_axi_DATA_WLAST,
        m_axi_DATA_WID,
        m_axi_DATA_WUSER,
        m_axi_DATA_ARVALID,
        m_axi_DATA_ARREADY,
        m_axi_DATA_ARADDR,
        m_axi_DATA_ARID,
        m_axi_DATA_ARLEN,
        m_axi_DATA_ARSIZE,
        m_axi_DATA_ARBURST,
        m_axi_DATA_ARLOCK,
        m_axi_DATA_ARCACHE,
        m_axi_DATA_ARPROT,
        m_axi_DATA_ARQOS,
        m_axi_DATA_ARREGION,
        m_axi_DATA_ARUSER,
        m_axi_DATA_RVALID,
        m_axi_DATA_RREADY,
        m_axi_DATA_RDATA,
        m_axi_DATA_RLAST,
        m_axi_DATA_RID,
        m_axi_DATA_RUSER,
        m_axi_DATA_RRESP,
        m_axi_DATA_BVALID,
        m_axi_DATA_BREADY,
        m_axi_DATA_BRESP,
        m_axi_DATA_BID,
        m_axi_DATA_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 29'd1;
parameter    ap_ST_fsm_state2 = 29'd2;
parameter    ap_ST_fsm_state3 = 29'd4;
parameter    ap_ST_fsm_state4 = 29'd8;
parameter    ap_ST_fsm_state5 = 29'd16;
parameter    ap_ST_fsm_state6 = 29'd32;
parameter    ap_ST_fsm_state7 = 29'd64;
parameter    ap_ST_fsm_state8 = 29'd128;
parameter    ap_ST_fsm_state9 = 29'd256;
parameter    ap_ST_fsm_state10 = 29'd512;
parameter    ap_ST_fsm_state11 = 29'd1024;
parameter    ap_ST_fsm_state12 = 29'd2048;
parameter    ap_ST_fsm_state13 = 29'd4096;
parameter    ap_ST_fsm_state14 = 29'd8192;
parameter    ap_ST_fsm_state15 = 29'd16384;
parameter    ap_ST_fsm_state16 = 29'd32768;
parameter    ap_ST_fsm_state17 = 29'd65536;
parameter    ap_ST_fsm_state18 = 29'd131072;
parameter    ap_ST_fsm_state19 = 29'd262144;
parameter    ap_ST_fsm_state20 = 29'd524288;
parameter    ap_ST_fsm_state21 = 29'd1048576;
parameter    ap_ST_fsm_state22 = 29'd2097152;
parameter    ap_ST_fsm_state23 = 29'd4194304;
parameter    ap_ST_fsm_state24 = 29'd8388608;
parameter    ap_ST_fsm_state25 = 29'd16777216;
parameter    ap_ST_fsm_state26 = 29'd33554432;
parameter    ap_ST_fsm_state27 = 29'd67108864;
parameter    ap_ST_fsm_state28 = 29'd134217728;
parameter    ap_ST_fsm_state29 = 29'd268435456;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_ID_WIDTH = 1;
parameter    C_M_AXI_DATA_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_USER_VALUE = 0;
parameter    C_M_AXI_DATA_PROT_VALUE = 0;
parameter    C_M_AXI_DATA_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_DATA_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_DATA_AWVALID;
input   m_axi_DATA_AWREADY;
output  [C_M_AXI_DATA_ADDR_WIDTH - 1:0] m_axi_DATA_AWADDR;
output  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_DATA_AWID;
output  [7:0] m_axi_DATA_AWLEN;
output  [2:0] m_axi_DATA_AWSIZE;
output  [1:0] m_axi_DATA_AWBURST;
output  [1:0] m_axi_DATA_AWLOCK;
output  [3:0] m_axi_DATA_AWCACHE;
output  [2:0] m_axi_DATA_AWPROT;
output  [3:0] m_axi_DATA_AWQOS;
output  [3:0] m_axi_DATA_AWREGION;
output  [C_M_AXI_DATA_AWUSER_WIDTH - 1:0] m_axi_DATA_AWUSER;
output   m_axi_DATA_WVALID;
input   m_axi_DATA_WREADY;
output  [C_M_AXI_DATA_DATA_WIDTH - 1:0] m_axi_DATA_WDATA;
output  [C_M_AXI_DATA_WSTRB_WIDTH - 1:0] m_axi_DATA_WSTRB;
output   m_axi_DATA_WLAST;
output  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_DATA_WID;
output  [C_M_AXI_DATA_WUSER_WIDTH - 1:0] m_axi_DATA_WUSER;
output   m_axi_DATA_ARVALID;
input   m_axi_DATA_ARREADY;
output  [C_M_AXI_DATA_ADDR_WIDTH - 1:0] m_axi_DATA_ARADDR;
output  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_DATA_ARID;
output  [7:0] m_axi_DATA_ARLEN;
output  [2:0] m_axi_DATA_ARSIZE;
output  [1:0] m_axi_DATA_ARBURST;
output  [1:0] m_axi_DATA_ARLOCK;
output  [3:0] m_axi_DATA_ARCACHE;
output  [2:0] m_axi_DATA_ARPROT;
output  [3:0] m_axi_DATA_ARQOS;
output  [3:0] m_axi_DATA_ARREGION;
output  [C_M_AXI_DATA_ARUSER_WIDTH - 1:0] m_axi_DATA_ARUSER;
input   m_axi_DATA_RVALID;
output   m_axi_DATA_RREADY;
input  [C_M_AXI_DATA_DATA_WIDTH - 1:0] m_axi_DATA_RDATA;
input   m_axi_DATA_RLAST;
input  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_DATA_RID;
input  [C_M_AXI_DATA_RUSER_WIDTH - 1:0] m_axi_DATA_RUSER;
input  [1:0] m_axi_DATA_RRESP;
input   m_axi_DATA_BVALID;
output   m_axi_DATA_BREADY;
input  [1:0] m_axi_DATA_BRESP;
input  [C_M_AXI_DATA_ID_WIDTH - 1:0] m_axi_DATA_BID;
input  [C_M_AXI_DATA_BUSER_WIDTH - 1:0] m_axi_DATA_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [28:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] data_in;
wire   [63:0] key_in;
wire   [63:0] data_out;
wire   [31:0] encrypt;
reg    DATA_blk_n_AR;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state11;
reg    DATA_blk_n_AW;
wire    ap_CS_fsm_state21;
reg    DATA_blk_n_B;
wire    ap_CS_fsm_state29;
reg   [63:0] data_out_read_reg_267;
reg   [61:0] trunc_ln_reg_272;
reg   [61:0] trunc_ln1_reg_278;
wire   [0:0] icmp_ln64_fu_221_p2;
reg   [0:0] icmp_ln64_reg_284;
wire  signed [61:0] trunc_ln2_fu_247_p4;
reg   [61:0] trunc_ln2_reg_298;
reg   [2:0] plaintext_address0;
reg    plaintext_ce0;
reg    plaintext_we0;
wire   [7:0] plaintext_q0;
reg   [2:0] plaintext_address1;
reg    plaintext_ce1;
reg    plaintext_we1;
wire   [7:0] plaintext_q1;
reg   [2:0] plaintext_1_address0;
reg    plaintext_1_ce0;
reg    plaintext_1_we0;
wire   [7:0] plaintext_1_q0;
reg   [2:0] plaintext_1_address1;
reg    plaintext_1_ce1;
reg    plaintext_1_we1;
wire   [7:0] plaintext_1_q1;
reg   [2:0] key_address0;
reg    key_ce0;
reg    key_we0;
wire   [7:0] key_q0;
reg   [2:0] key_address1;
reg    key_ce1;
reg    key_we1;
wire   [7:0] key_q1;
reg   [2:0] key_1_address0;
reg    key_1_ce0;
reg    key_1_we0;
wire   [7:0] key_1_q0;
reg   [2:0] key_1_address1;
reg    key_1_ce1;
reg    key_1_we1;
wire   [7:0] key_1_q1;
reg   [2:0] ciphertext_address0;
reg    ciphertext_ce0;
reg    ciphertext_we0;
reg   [7:0] ciphertext_d0;
wire   [7:0] ciphertext_q0;
reg   [2:0] ciphertext_address1;
reg    ciphertext_ce1;
reg    ciphertext_we1;
wire   [7:0] ciphertext_q1;
reg   [2:0] ciphertext_1_address0;
reg    ciphertext_1_ce0;
reg    ciphertext_1_we0;
reg   [7:0] ciphertext_1_d0;
wire   [7:0] ciphertext_1_q0;
reg   [2:0] ciphertext_1_address1;
reg    ciphertext_1_ce1;
reg    ciphertext_1_we1;
wire   [7:0] ciphertext_1_q1;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_done;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_idle;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_ready;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWVALID;
wire   [63:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWADDR;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWID;
wire   [31:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWLEN;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWSIZE;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWBURST;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWLOCK;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWCACHE;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWPROT;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWQOS;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWREGION;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWUSER;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WVALID;
wire   [31:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WDATA;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WSTRB;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WLAST;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WID;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WUSER;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARVALID;
wire   [63:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARADDR;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARID;
wire   [31:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARLEN;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARSIZE;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARBURST;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARLOCK;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARCACHE;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARPROT;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARQOS;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARREGION;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARUSER;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_RREADY;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_BREADY;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_address0;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_ce0;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_we0;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_d0;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_address1;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_ce1;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_we1;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_d1;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_address0;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_ce0;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_we0;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_d0;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_address1;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_ce1;
wire    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_we1;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_d1;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_done;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_idle;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_ready;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWVALID;
wire   [63:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWADDR;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWID;
wire   [31:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWLEN;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWSIZE;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWBURST;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWLOCK;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWCACHE;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWPROT;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWQOS;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWREGION;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWUSER;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WVALID;
wire   [31:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WDATA;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WSTRB;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WLAST;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WID;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WUSER;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARVALID;
wire   [63:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARADDR;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARID;
wire   [31:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARLEN;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARSIZE;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARBURST;
wire   [1:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARLOCK;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARCACHE;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARPROT;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARQOS;
wire   [3:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARREGION;
wire   [0:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARUSER;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_RREADY;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_BREADY;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_address0;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_ce0;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_we0;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_d0;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_address1;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_ce1;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_we1;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_d1;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_address0;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_ce0;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_we0;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_d0;
wire   [2:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_address1;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_ce1;
wire    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_we1;
wire   [7:0] grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_d1;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_done;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_idle;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_ready;
wire   [2:0] grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_address0;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_ce0;
wire   [2:0] grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_1_address0;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_1_ce0;
wire   [2:0] grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_address0;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_ce0;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_we0;
wire   [7:0] grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_d0;
wire   [2:0] grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_address0;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_ce0;
wire    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_we0;
wire   [7:0] grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_d0;
wire    grp_aes128_encrypt_fu_178_ap_start;
wire    grp_aes128_encrypt_fu_178_ap_done;
wire    grp_aes128_encrypt_fu_178_ap_idle;
wire    grp_aes128_encrypt_fu_178_ap_ready;
wire   [2:0] grp_aes128_encrypt_fu_178_plaintext_0_address0;
wire    grp_aes128_encrypt_fu_178_plaintext_0_ce0;
wire   [2:0] grp_aes128_encrypt_fu_178_plaintext_0_address1;
wire    grp_aes128_encrypt_fu_178_plaintext_0_ce1;
wire   [2:0] grp_aes128_encrypt_fu_178_plaintext_1_address0;
wire    grp_aes128_encrypt_fu_178_plaintext_1_ce0;
wire   [2:0] grp_aes128_encrypt_fu_178_plaintext_1_address1;
wire    grp_aes128_encrypt_fu_178_plaintext_1_ce1;
wire   [2:0] grp_aes128_encrypt_fu_178_key_0_address0;
wire    grp_aes128_encrypt_fu_178_key_0_ce0;
wire   [2:0] grp_aes128_encrypt_fu_178_key_0_address1;
wire    grp_aes128_encrypt_fu_178_key_0_ce1;
wire   [2:0] grp_aes128_encrypt_fu_178_key_1_address0;
wire    grp_aes128_encrypt_fu_178_key_1_ce0;
wire   [2:0] grp_aes128_encrypt_fu_178_key_1_address1;
wire    grp_aes128_encrypt_fu_178_key_1_ce1;
wire   [2:0] grp_aes128_encrypt_fu_178_ciphertext_0_address0;
wire    grp_aes128_encrypt_fu_178_ciphertext_0_ce0;
wire    grp_aes128_encrypt_fu_178_ciphertext_0_we0;
wire   [7:0] grp_aes128_encrypt_fu_178_ciphertext_0_d0;
wire   [2:0] grp_aes128_encrypt_fu_178_ciphertext_0_address1;
wire    grp_aes128_encrypt_fu_178_ciphertext_0_ce1;
wire    grp_aes128_encrypt_fu_178_ciphertext_0_we1;
wire   [7:0] grp_aes128_encrypt_fu_178_ciphertext_0_d1;
wire   [2:0] grp_aes128_encrypt_fu_178_ciphertext_1_address0;
wire    grp_aes128_encrypt_fu_178_ciphertext_1_ce0;
wire    grp_aes128_encrypt_fu_178_ciphertext_1_we0;
wire   [7:0] grp_aes128_encrypt_fu_178_ciphertext_1_d0;
wire   [2:0] grp_aes128_encrypt_fu_178_ciphertext_1_address1;
wire    grp_aes128_encrypt_fu_178_ciphertext_1_ce1;
wire    grp_aes128_encrypt_fu_178_ciphertext_1_we1;
wire   [7:0] grp_aes128_encrypt_fu_178_ciphertext_1_d1;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_done;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_idle;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_ready;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWVALID;
wire   [63:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWADDR;
wire   [0:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWID;
wire   [31:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWLEN;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWSIZE;
wire   [1:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWBURST;
wire   [1:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWLOCK;
wire   [3:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWCACHE;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWPROT;
wire   [3:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWQOS;
wire   [3:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWREGION;
wire   [0:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWUSER;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WVALID;
wire   [31:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WDATA;
wire   [3:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WSTRB;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WLAST;
wire   [0:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WID;
wire   [0:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WUSER;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARVALID;
wire   [63:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARADDR;
wire   [0:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARID;
wire   [31:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARLEN;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARSIZE;
wire   [1:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARBURST;
wire   [1:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARLOCK;
wire   [3:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARCACHE;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARPROT;
wire   [3:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARQOS;
wire   [3:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARREGION;
wire   [0:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARUSER;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_RREADY;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_BREADY;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_address0;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_ce0;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_address1;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_ce1;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_address0;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_ce0;
wire   [2:0] grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_address1;
wire    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_ce1;
reg    DATA_AWVALID;
wire    DATA_AWREADY;
reg   [63:0] DATA_AWADDR;
reg   [31:0] DATA_AWLEN;
reg    DATA_WVALID;
wire    DATA_WREADY;
reg    DATA_ARVALID;
wire    DATA_ARREADY;
reg   [63:0] DATA_ARADDR;
reg   [31:0] DATA_ARLEN;
wire    DATA_RVALID;
reg    DATA_RREADY;
wire   [31:0] DATA_RDATA;
wire   [8:0] DATA_RFIFONUM;
wire    DATA_BVALID;
reg    DATA_BREADY;
reg    grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg    grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start_reg;
wire    ap_CS_fsm_state22;
reg    grp_aes128_encrypt_fu_178_ap_start_reg;
wire    ap_CS_fsm_state20;
reg    grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start_reg;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire  signed [63:0] sext_ln43_fu_227_p1;
wire  signed [63:0] sext_ln52_fu_237_p1;
wire  signed [63:0] sext_ln77_fu_256_p1;
reg    ap_block_state21_on_subcall_done;
reg   [28:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 29'd1;
#0 grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start_reg = 1'b0;
#0 grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start_reg = 1'b0;
#0 grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start_reg = 1'b0;
#0 grp_aes128_encrypt_fu_178_ap_start_reg = 1'b0;
#0 grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start_reg = 1'b0;
end

aes128_top_plaintext_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
plaintext_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(plaintext_address0),
    .ce0(plaintext_ce0),
    .we0(plaintext_we0),
    .d0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_d0),
    .q0(plaintext_q0),
    .address1(plaintext_address1),
    .ce1(plaintext_ce1),
    .we1(plaintext_we1),
    .d1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_d1),
    .q1(plaintext_q1)
);

aes128_top_plaintext_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
plaintext_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(plaintext_1_address0),
    .ce0(plaintext_1_ce0),
    .we0(plaintext_1_we0),
    .d0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_d0),
    .q0(plaintext_1_q0),
    .address1(plaintext_1_address1),
    .ce1(plaintext_1_ce1),
    .we1(plaintext_1_we1),
    .d1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_d1),
    .q1(plaintext_1_q1)
);

aes128_top_plaintext_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
key_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(key_address0),
    .ce0(key_ce0),
    .we0(key_we0),
    .d0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_d0),
    .q0(key_q0),
    .address1(key_address1),
    .ce1(key_ce1),
    .we1(key_we1),
    .d1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_d1),
    .q1(key_q1)
);

aes128_top_plaintext_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
key_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(key_1_address0),
    .ce0(key_1_ce0),
    .we0(key_1_we0),
    .d0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_d0),
    .q0(key_1_q0),
    .address1(key_1_address1),
    .ce1(key_1_ce1),
    .we1(key_1_we1),
    .d1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_d1),
    .q1(key_1_q1)
);

aes128_top_plaintext_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
ciphertext_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(ciphertext_address0),
    .ce0(ciphertext_ce0),
    .we0(ciphertext_we0),
    .d0(ciphertext_d0),
    .q0(ciphertext_q0),
    .address1(ciphertext_address1),
    .ce1(ciphertext_ce1),
    .we1(ciphertext_we1),
    .d1(grp_aes128_encrypt_fu_178_ciphertext_0_d1),
    .q1(ciphertext_q1)
);

aes128_top_plaintext_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
ciphertext_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(ciphertext_1_address0),
    .ce0(ciphertext_1_ce0),
    .we0(ciphertext_1_we0),
    .d0(ciphertext_1_d0),
    .q0(ciphertext_1_q0),
    .address1(ciphertext_1_address1),
    .ce1(ciphertext_1_ce1),
    .we1(ciphertext_1_we1),
    .d1(grp_aes128_encrypt_fu_178_ciphertext_1_d1),
    .q1(ciphertext_1_q1)
);

aes128_top_aes128_top_Pipeline_LOAD_DATA grp_aes128_top_Pipeline_LOAD_DATA_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start),
    .ap_done(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_done),
    .ap_idle(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_idle),
    .ap_ready(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_ready),
    .m_axi_DATA_AWVALID(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWVALID),
    .m_axi_DATA_AWREADY(1'b0),
    .m_axi_DATA_AWADDR(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWADDR),
    .m_axi_DATA_AWID(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWID),
    .m_axi_DATA_AWLEN(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWLEN),
    .m_axi_DATA_AWSIZE(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWSIZE),
    .m_axi_DATA_AWBURST(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWBURST),
    .m_axi_DATA_AWLOCK(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWLOCK),
    .m_axi_DATA_AWCACHE(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWCACHE),
    .m_axi_DATA_AWPROT(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWPROT),
    .m_axi_DATA_AWQOS(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWQOS),
    .m_axi_DATA_AWREGION(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWREGION),
    .m_axi_DATA_AWUSER(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_AWUSER),
    .m_axi_DATA_WVALID(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WVALID),
    .m_axi_DATA_WREADY(1'b0),
    .m_axi_DATA_WDATA(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WDATA),
    .m_axi_DATA_WSTRB(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WSTRB),
    .m_axi_DATA_WLAST(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WLAST),
    .m_axi_DATA_WID(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WID),
    .m_axi_DATA_WUSER(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_WUSER),
    .m_axi_DATA_ARVALID(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARVALID),
    .m_axi_DATA_ARREADY(DATA_ARREADY),
    .m_axi_DATA_ARADDR(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARADDR),
    .m_axi_DATA_ARID(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARID),
    .m_axi_DATA_ARLEN(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARLEN),
    .m_axi_DATA_ARSIZE(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARSIZE),
    .m_axi_DATA_ARBURST(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARBURST),
    .m_axi_DATA_ARLOCK(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARLOCK),
    .m_axi_DATA_ARCACHE(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARCACHE),
    .m_axi_DATA_ARPROT(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARPROT),
    .m_axi_DATA_ARQOS(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARQOS),
    .m_axi_DATA_ARREGION(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARREGION),
    .m_axi_DATA_ARUSER(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARUSER),
    .m_axi_DATA_RVALID(DATA_RVALID),
    .m_axi_DATA_RREADY(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_RREADY),
    .m_axi_DATA_RDATA(DATA_RDATA),
    .m_axi_DATA_RLAST(1'b0),
    .m_axi_DATA_RID(1'd0),
    .m_axi_DATA_RFIFONUM(DATA_RFIFONUM),
    .m_axi_DATA_RUSER(1'd0),
    .m_axi_DATA_RRESP(2'd0),
    .m_axi_DATA_BVALID(1'b0),
    .m_axi_DATA_BREADY(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_BREADY),
    .m_axi_DATA_BRESP(2'd0),
    .m_axi_DATA_BID(1'd0),
    .m_axi_DATA_BUSER(1'd0),
    .sext_ln43(trunc_ln_reg_272),
    .plaintext_1_address0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_address0),
    .plaintext_1_ce0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_ce0),
    .plaintext_1_we0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_we0),
    .plaintext_1_d0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_d0),
    .plaintext_1_address1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_address1),
    .plaintext_1_ce1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_ce1),
    .plaintext_1_we1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_we1),
    .plaintext_1_d1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_d1),
    .plaintext_address0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_address0),
    .plaintext_ce0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_ce0),
    .plaintext_we0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_we0),
    .plaintext_d0(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_d0),
    .plaintext_address1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_address1),
    .plaintext_ce1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_ce1),
    .plaintext_we1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_we1),
    .plaintext_d1(grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_d1)
);

aes128_top_aes128_top_Pipeline_LOAD_KEY grp_aes128_top_Pipeline_LOAD_KEY_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start),
    .ap_done(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_done),
    .ap_idle(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_idle),
    .ap_ready(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_ready),
    .m_axi_DATA_AWVALID(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWVALID),
    .m_axi_DATA_AWREADY(1'b0),
    .m_axi_DATA_AWADDR(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWADDR),
    .m_axi_DATA_AWID(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWID),
    .m_axi_DATA_AWLEN(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWLEN),
    .m_axi_DATA_AWSIZE(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWSIZE),
    .m_axi_DATA_AWBURST(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWBURST),
    .m_axi_DATA_AWLOCK(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWLOCK),
    .m_axi_DATA_AWCACHE(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWCACHE),
    .m_axi_DATA_AWPROT(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWPROT),
    .m_axi_DATA_AWQOS(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWQOS),
    .m_axi_DATA_AWREGION(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWREGION),
    .m_axi_DATA_AWUSER(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_AWUSER),
    .m_axi_DATA_WVALID(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WVALID),
    .m_axi_DATA_WREADY(1'b0),
    .m_axi_DATA_WDATA(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WDATA),
    .m_axi_DATA_WSTRB(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WSTRB),
    .m_axi_DATA_WLAST(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WLAST),
    .m_axi_DATA_WID(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WID),
    .m_axi_DATA_WUSER(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_WUSER),
    .m_axi_DATA_ARVALID(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARVALID),
    .m_axi_DATA_ARREADY(DATA_ARREADY),
    .m_axi_DATA_ARADDR(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARADDR),
    .m_axi_DATA_ARID(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARID),
    .m_axi_DATA_ARLEN(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARLEN),
    .m_axi_DATA_ARSIZE(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARSIZE),
    .m_axi_DATA_ARBURST(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARBURST),
    .m_axi_DATA_ARLOCK(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARLOCK),
    .m_axi_DATA_ARCACHE(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARCACHE),
    .m_axi_DATA_ARPROT(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARPROT),
    .m_axi_DATA_ARQOS(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARQOS),
    .m_axi_DATA_ARREGION(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARREGION),
    .m_axi_DATA_ARUSER(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARUSER),
    .m_axi_DATA_RVALID(DATA_RVALID),
    .m_axi_DATA_RREADY(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_RREADY),
    .m_axi_DATA_RDATA(DATA_RDATA),
    .m_axi_DATA_RLAST(1'b0),
    .m_axi_DATA_RID(1'd0),
    .m_axi_DATA_RFIFONUM(DATA_RFIFONUM),
    .m_axi_DATA_RUSER(1'd0),
    .m_axi_DATA_RRESP(2'd0),
    .m_axi_DATA_BVALID(1'b0),
    .m_axi_DATA_BREADY(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_BREADY),
    .m_axi_DATA_BRESP(2'd0),
    .m_axi_DATA_BID(1'd0),
    .m_axi_DATA_BUSER(1'd0),
    .sext_ln52(trunc_ln1_reg_278),
    .key_1_address0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_address0),
    .key_1_ce0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_ce0),
    .key_1_we0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_we0),
    .key_1_d0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_d0),
    .key_1_address1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_address1),
    .key_1_ce1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_ce1),
    .key_1_we1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_we1),
    .key_1_d1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_d1),
    .key_address0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_address0),
    .key_ce0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_ce0),
    .key_we0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_we0),
    .key_d0(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_d0),
    .key_address1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_address1),
    .key_ce1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_ce1),
    .key_we1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_we1),
    .key_d1(grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_d1)
);

aes128_top_aes128_top_Pipeline_VITIS_LOOP_69_1 grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start),
    .ap_done(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_done),
    .ap_idle(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_idle),
    .ap_ready(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_ready),
    .plaintext_address0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_address0),
    .plaintext_ce0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_ce0),
    .plaintext_q0(plaintext_q0),
    .plaintext_1_address0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_1_address0),
    .plaintext_1_ce0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_1_ce0),
    .plaintext_1_q0(plaintext_1_q0),
    .ciphertext_address0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_address0),
    .ciphertext_ce0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_ce0),
    .ciphertext_we0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_we0),
    .ciphertext_d0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_d0),
    .ciphertext_1_address0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_address0),
    .ciphertext_1_ce0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_ce0),
    .ciphertext_1_we0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_we0),
    .ciphertext_1_d0(grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_d0)
);

aes128_top_aes128_encrypt grp_aes128_encrypt_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_aes128_encrypt_fu_178_ap_start),
    .ap_done(grp_aes128_encrypt_fu_178_ap_done),
    .ap_idle(grp_aes128_encrypt_fu_178_ap_idle),
    .ap_ready(grp_aes128_encrypt_fu_178_ap_ready),
    .plaintext_0_address0(grp_aes128_encrypt_fu_178_plaintext_0_address0),
    .plaintext_0_ce0(grp_aes128_encrypt_fu_178_plaintext_0_ce0),
    .plaintext_0_q0(plaintext_q0),
    .plaintext_0_address1(grp_aes128_encrypt_fu_178_plaintext_0_address1),
    .plaintext_0_ce1(grp_aes128_encrypt_fu_178_plaintext_0_ce1),
    .plaintext_0_q1(plaintext_q1),
    .plaintext_1_address0(grp_aes128_encrypt_fu_178_plaintext_1_address0),
    .plaintext_1_ce0(grp_aes128_encrypt_fu_178_plaintext_1_ce0),
    .plaintext_1_q0(plaintext_1_q0),
    .plaintext_1_address1(grp_aes128_encrypt_fu_178_plaintext_1_address1),
    .plaintext_1_ce1(grp_aes128_encrypt_fu_178_plaintext_1_ce1),
    .plaintext_1_q1(plaintext_1_q1),
    .key_0_address0(grp_aes128_encrypt_fu_178_key_0_address0),
    .key_0_ce0(grp_aes128_encrypt_fu_178_key_0_ce0),
    .key_0_q0(key_q0),
    .key_0_address1(grp_aes128_encrypt_fu_178_key_0_address1),
    .key_0_ce1(grp_aes128_encrypt_fu_178_key_0_ce1),
    .key_0_q1(key_q1),
    .key_1_address0(grp_aes128_encrypt_fu_178_key_1_address0),
    .key_1_ce0(grp_aes128_encrypt_fu_178_key_1_ce0),
    .key_1_q0(key_1_q0),
    .key_1_address1(grp_aes128_encrypt_fu_178_key_1_address1),
    .key_1_ce1(grp_aes128_encrypt_fu_178_key_1_ce1),
    .key_1_q1(key_1_q1),
    .ciphertext_0_address0(grp_aes128_encrypt_fu_178_ciphertext_0_address0),
    .ciphertext_0_ce0(grp_aes128_encrypt_fu_178_ciphertext_0_ce0),
    .ciphertext_0_we0(grp_aes128_encrypt_fu_178_ciphertext_0_we0),
    .ciphertext_0_d0(grp_aes128_encrypt_fu_178_ciphertext_0_d0),
    .ciphertext_0_address1(grp_aes128_encrypt_fu_178_ciphertext_0_address1),
    .ciphertext_0_ce1(grp_aes128_encrypt_fu_178_ciphertext_0_ce1),
    .ciphertext_0_we1(grp_aes128_encrypt_fu_178_ciphertext_0_we1),
    .ciphertext_0_d1(grp_aes128_encrypt_fu_178_ciphertext_0_d1),
    .ciphertext_1_address0(grp_aes128_encrypt_fu_178_ciphertext_1_address0),
    .ciphertext_1_ce0(grp_aes128_encrypt_fu_178_ciphertext_1_ce0),
    .ciphertext_1_we0(grp_aes128_encrypt_fu_178_ciphertext_1_we0),
    .ciphertext_1_d0(grp_aes128_encrypt_fu_178_ciphertext_1_d0),
    .ciphertext_1_address1(grp_aes128_encrypt_fu_178_ciphertext_1_address1),
    .ciphertext_1_ce1(grp_aes128_encrypt_fu_178_ciphertext_1_ce1),
    .ciphertext_1_we1(grp_aes128_encrypt_fu_178_ciphertext_1_we1),
    .ciphertext_1_d1(grp_aes128_encrypt_fu_178_ciphertext_1_d1)
);

aes128_top_aes128_top_Pipeline_STORE_DATA grp_aes128_top_Pipeline_STORE_DATA_fu_192(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start),
    .ap_done(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_done),
    .ap_idle(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_idle),
    .ap_ready(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_ready),
    .m_axi_DATA_AWVALID(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWVALID),
    .m_axi_DATA_AWREADY(DATA_AWREADY),
    .m_axi_DATA_AWADDR(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWADDR),
    .m_axi_DATA_AWID(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWID),
    .m_axi_DATA_AWLEN(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWLEN),
    .m_axi_DATA_AWSIZE(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWSIZE),
    .m_axi_DATA_AWBURST(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWBURST),
    .m_axi_DATA_AWLOCK(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWLOCK),
    .m_axi_DATA_AWCACHE(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWCACHE),
    .m_axi_DATA_AWPROT(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWPROT),
    .m_axi_DATA_AWQOS(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWQOS),
    .m_axi_DATA_AWREGION(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWREGION),
    .m_axi_DATA_AWUSER(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWUSER),
    .m_axi_DATA_WVALID(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WVALID),
    .m_axi_DATA_WREADY(DATA_WREADY),
    .m_axi_DATA_WDATA(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WDATA),
    .m_axi_DATA_WSTRB(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WSTRB),
    .m_axi_DATA_WLAST(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WLAST),
    .m_axi_DATA_WID(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WID),
    .m_axi_DATA_WUSER(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WUSER),
    .m_axi_DATA_ARVALID(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARVALID),
    .m_axi_DATA_ARREADY(1'b0),
    .m_axi_DATA_ARADDR(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARADDR),
    .m_axi_DATA_ARID(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARID),
    .m_axi_DATA_ARLEN(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARLEN),
    .m_axi_DATA_ARSIZE(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARSIZE),
    .m_axi_DATA_ARBURST(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARBURST),
    .m_axi_DATA_ARLOCK(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARLOCK),
    .m_axi_DATA_ARCACHE(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARCACHE),
    .m_axi_DATA_ARPROT(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARPROT),
    .m_axi_DATA_ARQOS(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARQOS),
    .m_axi_DATA_ARREGION(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARREGION),
    .m_axi_DATA_ARUSER(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_ARUSER),
    .m_axi_DATA_RVALID(1'b0),
    .m_axi_DATA_RREADY(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_RREADY),
    .m_axi_DATA_RDATA(32'd0),
    .m_axi_DATA_RLAST(1'b0),
    .m_axi_DATA_RID(1'd0),
    .m_axi_DATA_RFIFONUM(9'd0),
    .m_axi_DATA_RUSER(1'd0),
    .m_axi_DATA_RRESP(2'd0),
    .m_axi_DATA_BVALID(DATA_BVALID),
    .m_axi_DATA_BREADY(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_BREADY),
    .m_axi_DATA_BRESP(2'd0),
    .m_axi_DATA_BID(1'd0),
    .m_axi_DATA_BUSER(1'd0),
    .sext_ln77(trunc_ln2_reg_298),
    .ciphertext_address0(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_address0),
    .ciphertext_ce0(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_ce0),
    .ciphertext_q0(ciphertext_q0),
    .ciphertext_address1(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_address1),
    .ciphertext_ce1(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_ce1),
    .ciphertext_q1(ciphertext_q1),
    .ciphertext_1_address0(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_address0),
    .ciphertext_1_ce0(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_ce0),
    .ciphertext_1_q0(ciphertext_1_q0),
    .ciphertext_1_address1(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_address1),
    .ciphertext_1_ce1(grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_ce1),
    .ciphertext_1_q1(ciphertext_1_q1)
);

aes128_top_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .data_in(data_in),
    .key_in(key_in),
    .data_out(data_out),
    .encrypt(encrypt),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

aes128_top_DATA_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_DATA_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA_CACHE_VALUE ),
    .USER_DW( 32 ),
    .USER_AW( 64 ))
DATA_m_axi_U(
    .AWVALID(m_axi_DATA_AWVALID),
    .AWREADY(m_axi_DATA_AWREADY),
    .AWADDR(m_axi_DATA_AWADDR),
    .AWID(m_axi_DATA_AWID),
    .AWLEN(m_axi_DATA_AWLEN),
    .AWSIZE(m_axi_DATA_AWSIZE),
    .AWBURST(m_axi_DATA_AWBURST),
    .AWLOCK(m_axi_DATA_AWLOCK),
    .AWCACHE(m_axi_DATA_AWCACHE),
    .AWPROT(m_axi_DATA_AWPROT),
    .AWQOS(m_axi_DATA_AWQOS),
    .AWREGION(m_axi_DATA_AWREGION),
    .AWUSER(m_axi_DATA_AWUSER),
    .WVALID(m_axi_DATA_WVALID),
    .WREADY(m_axi_DATA_WREADY),
    .WDATA(m_axi_DATA_WDATA),
    .WSTRB(m_axi_DATA_WSTRB),
    .WLAST(m_axi_DATA_WLAST),
    .WID(m_axi_DATA_WID),
    .WUSER(m_axi_DATA_WUSER),
    .ARVALID(m_axi_DATA_ARVALID),
    .ARREADY(m_axi_DATA_ARREADY),
    .ARADDR(m_axi_DATA_ARADDR),
    .ARID(m_axi_DATA_ARID),
    .ARLEN(m_axi_DATA_ARLEN),
    .ARSIZE(m_axi_DATA_ARSIZE),
    .ARBURST(m_axi_DATA_ARBURST),
    .ARLOCK(m_axi_DATA_ARLOCK),
    .ARCACHE(m_axi_DATA_ARCACHE),
    .ARPROT(m_axi_DATA_ARPROT),
    .ARQOS(m_axi_DATA_ARQOS),
    .ARREGION(m_axi_DATA_ARREGION),
    .ARUSER(m_axi_DATA_ARUSER),
    .RVALID(m_axi_DATA_RVALID),
    .RREADY(m_axi_DATA_RREADY),
    .RDATA(m_axi_DATA_RDATA),
    .RLAST(m_axi_DATA_RLAST),
    .RID(m_axi_DATA_RID),
    .RUSER(m_axi_DATA_RUSER),
    .RRESP(m_axi_DATA_RRESP),
    .BVALID(m_axi_DATA_BVALID),
    .BREADY(m_axi_DATA_BREADY),
    .BRESP(m_axi_DATA_BRESP),
    .BID(m_axi_DATA_BID),
    .BUSER(m_axi_DATA_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(DATA_ARVALID),
    .I_ARREADY(DATA_ARREADY),
    .I_ARADDR(DATA_ARADDR),
    .I_ARLEN(DATA_ARLEN),
    .I_RVALID(DATA_RVALID),
    .I_RREADY(DATA_RREADY),
    .I_RDATA(DATA_RDATA),
    .I_RFIFONUM(DATA_RFIFONUM),
    .I_AWVALID(DATA_AWVALID),
    .I_AWREADY(DATA_AWREADY),
    .I_AWADDR(DATA_AWADDR),
    .I_AWLEN(DATA_AWLEN),
    .I_WVALID(DATA_WVALID),
    .I_WREADY(DATA_WREADY),
    .I_WDATA(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WDATA),
    .I_WSTRB(grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WSTRB),
    .I_BVALID(DATA_BVALID),
    .I_BREADY(DATA_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_aes128_encrypt_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_aes128_encrypt_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_aes128_encrypt_fu_178_ap_ready == 1'b1)) begin
            grp_aes128_encrypt_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_ready == 1'b1)) begin
            grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start_reg <= 1'b1;
        end else if ((grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_ready == 1'b1)) begin
            grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start_reg <= 1'b1;
        end else if ((grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_ready == 1'b1)) begin
            grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln64_reg_284 == 1'd1))) begin
            grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_ready == 1'b1)) begin
            grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_out_read_reg_267 <= data_out;
        icmp_ln64_reg_284 <= icmp_ln64_fu_221_p2;
        trunc_ln1_reg_278 <= {{key_in[63:2]}};
        trunc_ln_reg_272 <= {{data_in[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        trunc_ln2_reg_298 <= {{data_out_read_reg_267[63:2]}};
    end
end

always @ (*) begin
    if (((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state11))) begin
        DATA_ARADDR = sext_ln52_fu_237_p1;
    end else if (((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        DATA_ARADDR = sext_ln43_fu_227_p1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        DATA_ARADDR = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        DATA_ARADDR = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARADDR;
    end else begin
        DATA_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state2)))) begin
        DATA_ARLEN = 32'd4;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        DATA_ARLEN = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        DATA_ARLEN = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARLEN;
    end else begin
        DATA_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state2)))) begin
        DATA_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        DATA_ARVALID = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        DATA_ARVALID = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_ARVALID;
    end else begin
        DATA_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state21_on_subcall_done) | (1'b0 == DATA_AWREADY)) & (1'b1 == ap_CS_fsm_state21))) begin
        DATA_AWADDR = sext_ln77_fu_256_p1;
    end else if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23))) begin
        DATA_AWADDR = grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWADDR;
    end else begin
        DATA_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state21_on_subcall_done) | (1'b0 == DATA_AWREADY)) & (1'b1 == ap_CS_fsm_state21))) begin
        DATA_AWLEN = 32'd4;
    end else if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23))) begin
        DATA_AWLEN = grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWLEN;
    end else begin
        DATA_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state21_on_subcall_done) | (1'b0 == DATA_AWREADY)) & (1'b1 == ap_CS_fsm_state21))) begin
        DATA_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23))) begin
        DATA_AWVALID = grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_AWVALID;
    end else begin
        DATA_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == DATA_BVALID) & (1'b1 == ap_CS_fsm_state29))) begin
        DATA_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23))) begin
        DATA_BREADY = grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_BREADY;
    end else begin
        DATA_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        DATA_RREADY = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_m_axi_DATA_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        DATA_RREADY = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_m_axi_DATA_RREADY;
    end else begin
        DATA_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23))) begin
        DATA_WVALID = grp_aes128_top_Pipeline_STORE_DATA_fu_192_m_axi_DATA_WVALID;
    end else begin
        DATA_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        DATA_blk_n_AR = m_axi_DATA_ARREADY;
    end else begin
        DATA_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        DATA_blk_n_AW = m_axi_DATA_AWREADY;
    end else begin
        DATA_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        DATA_blk_n_B = m_axi_DATA_BVALID;
    end else begin
        DATA_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == DATA_ARREADY)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state21_on_subcall_done) | (1'b0 == DATA_AWREADY))) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((1'b0 == DATA_BVALID)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == DATA_ARREADY)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == DATA_BVALID) & (1'b1 == ap_CS_fsm_state29))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == DATA_BVALID) & (1'b1 == ap_CS_fsm_state29))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_1_address0 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_address0;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_1_address0 = grp_aes128_encrypt_fu_178_ciphertext_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_1_address0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_address0;
    end else begin
        ciphertext_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_1_address1 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_address1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_1_address1 = grp_aes128_encrypt_fu_178_ciphertext_1_address1;
    end else begin
        ciphertext_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_1_ce0 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_ce0;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_1_ce0 = grp_aes128_encrypt_fu_178_ciphertext_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_1_ce0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_ce0;
    end else begin
        ciphertext_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_1_ce1 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_1_ce1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_1_ce1 = grp_aes128_encrypt_fu_178_ciphertext_1_ce1;
    end else begin
        ciphertext_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_1_d0 = grp_aes128_encrypt_fu_178_ciphertext_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_1_d0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_d0;
    end else begin
        ciphertext_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_1_we0 = grp_aes128_encrypt_fu_178_ciphertext_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_1_we0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_1_we0;
    end else begin
        ciphertext_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_1_we1 = grp_aes128_encrypt_fu_178_ciphertext_1_we1;
    end else begin
        ciphertext_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_address0 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_address0;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_address0 = grp_aes128_encrypt_fu_178_ciphertext_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_address0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_address0;
    end else begin
        ciphertext_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_address1 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_address1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_address1 = grp_aes128_encrypt_fu_178_ciphertext_0_address1;
    end else begin
        ciphertext_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_ce0 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_ce0;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_ce0 = grp_aes128_encrypt_fu_178_ciphertext_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_ce0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_ce0;
    end else begin
        ciphertext_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ciphertext_ce1 = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ciphertext_ce1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_ce1 = grp_aes128_encrypt_fu_178_ciphertext_0_ce1;
    end else begin
        ciphertext_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_d0 = grp_aes128_encrypt_fu_178_ciphertext_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_d0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_d0;
    end else begin
        ciphertext_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_we0 = grp_aes128_encrypt_fu_178_ciphertext_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        ciphertext_we0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ciphertext_we0;
    end else begin
        ciphertext_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        ciphertext_we1 = grp_aes128_encrypt_fu_178_ciphertext_0_we1;
    end else begin
        ciphertext_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_1_address0 = grp_aes128_encrypt_fu_178_key_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_1_address0 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_address0;
    end else begin
        key_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_1_address1 = grp_aes128_encrypt_fu_178_key_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_1_address1 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_address1;
    end else begin
        key_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_1_ce0 = grp_aes128_encrypt_fu_178_key_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_1_ce0 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_ce0;
    end else begin
        key_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_1_ce1 = grp_aes128_encrypt_fu_178_key_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_1_ce1 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_ce1;
    end else begin
        key_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        key_1_we0 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_we0;
    end else begin
        key_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        key_1_we1 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_1_we1;
    end else begin
        key_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_address0 = grp_aes128_encrypt_fu_178_key_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_address0 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_address0;
    end else begin
        key_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_address1 = grp_aes128_encrypt_fu_178_key_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_address1 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_address1;
    end else begin
        key_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_ce0 = grp_aes128_encrypt_fu_178_key_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_ce0 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_ce0;
    end else begin
        key_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        key_ce1 = grp_aes128_encrypt_fu_178_key_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        key_ce1 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_ce1;
    end else begin
        key_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        key_we0 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_we0;
    end else begin
        key_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        key_we1 = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_key_we1;
    end else begin
        key_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_1_address0 = grp_aes128_encrypt_fu_178_plaintext_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        plaintext_1_address0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_1_address0 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_address0;
    end else begin
        plaintext_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_1_address1 = grp_aes128_encrypt_fu_178_plaintext_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_1_address1 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_address1;
    end else begin
        plaintext_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_1_ce0 = grp_aes128_encrypt_fu_178_plaintext_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        plaintext_1_ce0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_1_ce0 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_ce0;
    end else begin
        plaintext_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_1_ce1 = grp_aes128_encrypt_fu_178_plaintext_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_1_ce1 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_ce1;
    end else begin
        plaintext_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_1_we0 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_we0;
    end else begin
        plaintext_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_1_we1 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_1_we1;
    end else begin
        plaintext_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_address0 = grp_aes128_encrypt_fu_178_plaintext_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        plaintext_address0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_address0 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_address0;
    end else begin
        plaintext_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_address1 = grp_aes128_encrypt_fu_178_plaintext_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_address1 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_address1;
    end else begin
        plaintext_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_ce0 = grp_aes128_encrypt_fu_178_plaintext_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        plaintext_ce0 = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_plaintext_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_ce0 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_ce0;
    end else begin
        plaintext_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln64_reg_284 == 1'd0))) begin
        plaintext_ce1 = grp_aes128_encrypt_fu_178_plaintext_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_ce1 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_ce1;
    end else begin
        plaintext_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_we0 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_we0;
    end else begin
        plaintext_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        plaintext_we1 = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_plaintext_we1;
    end else begin
        plaintext_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == DATA_ARREADY) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln64_reg_284 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else if (((grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln64_reg_284 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if ((~((1'b1 == ap_block_state21_on_subcall_done) | (1'b0 == DATA_AWREADY)) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((1'b1 == DATA_BVALID) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state21_on_subcall_done = ((grp_aes128_encrypt_fu_178_ap_done == 1'b0) & (icmp_ln64_reg_284 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_aes128_encrypt_fu_178_ap_start = grp_aes128_encrypt_fu_178_ap_start_reg;

assign grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start = grp_aes128_top_Pipeline_LOAD_DATA_fu_152_ap_start_reg;

assign grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start = grp_aes128_top_Pipeline_LOAD_KEY_fu_161_ap_start_reg;

assign grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start = grp_aes128_top_Pipeline_STORE_DATA_fu_192_ap_start_reg;

assign grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start = grp_aes128_top_Pipeline_VITIS_LOOP_69_1_fu_170_ap_start_reg;

assign icmp_ln64_fu_221_p2 = ((encrypt == 32'd0) ? 1'b1 : 1'b0);

assign sext_ln43_fu_227_p1 = $signed(trunc_ln_reg_272);

assign sext_ln52_fu_237_p1 = $signed(trunc_ln1_reg_278);

assign sext_ln77_fu_256_p1 = trunc_ln2_fu_247_p4;

assign trunc_ln2_fu_247_p4 = {{data_out_read_reg_267[63:2]}};

endmodule //aes128_top
