-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sha256_top_sha256_top_Pipeline_LOAD_BLOCK is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_DATA_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_AWREADY : IN STD_LOGIC;
    m_axi_DATA_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_DATA_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_WVALID : OUT STD_LOGIC;
    m_axi_DATA_WREADY : IN STD_LOGIC;
    m_axi_DATA_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_WLAST : OUT STD_LOGIC;
    m_axi_DATA_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_ARREADY : IN STD_LOGIC;
    m_axi_DATA_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_DATA_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RVALID : IN STD_LOGIC;
    m_axi_DATA_RREADY : OUT STD_LOGIC;
    m_axi_DATA_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_RLAST : IN STD_LOGIC;
    m_axi_DATA_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_DATA_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_BVALID : IN STD_LOGIC;
    m_axi_DATA_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln60 : IN STD_LOGIC_VECTOR (62 downto 0);
    sext_ln52 : IN STD_LOGIC_VECTOR (61 downto 0);
    zext_ln52 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_15_out_ap_vld : OUT STD_LOGIC;
    block_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_14_out_ap_vld : OUT STD_LOGIC;
    block_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_13_out_ap_vld : OUT STD_LOGIC;
    block_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_12_out_ap_vld : OUT STD_LOGIC;
    block_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_11_out_ap_vld : OUT STD_LOGIC;
    block_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_10_out_ap_vld : OUT STD_LOGIC;
    block_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_9_out_ap_vld : OUT STD_LOGIC;
    block_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_8_out_ap_vld : OUT STD_LOGIC;
    block_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_7_out_ap_vld : OUT STD_LOGIC;
    block_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_6_out_ap_vld : OUT STD_LOGIC;
    block_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_5_out_ap_vld : OUT STD_LOGIC;
    block_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_4_out_ap_vld : OUT STD_LOGIC;
    block_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_3_out_ap_vld : OUT STD_LOGIC;
    block_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_2_out_ap_vld : OUT STD_LOGIC;
    block_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_1_out_ap_vld : OUT STD_LOGIC;
    block_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    block_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sha256_top_sha256_top_Pipeline_LOAD_BLOCK is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal DATA_blk_n_AR : STD_LOGIC;
    signal DATA_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal trunc_ln60_fu_361_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln60_reg_626 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state8_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln58_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state8 : STD_LOGIC;
    signal sext_ln60_cast_fu_330_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_120 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln58_fu_355_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal block_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal block_1_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_2_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_3_fu_136 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_4_fu_140 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_5_fu_144 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_6_fu_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_7_fu_152 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_8_fu_156 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_9_fu_160 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_10_fu_164 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_11_fu_168 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_12_fu_172 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_13_fu_176 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_14_fu_180 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_15_fu_184 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state8);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((m_axi_DATA_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_120 <= ap_const_lv5_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln58_fu_349_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_fu_120 <= add_ln58_fu_355_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_10_fu_164 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_11_fu_168 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_12_fu_172 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_13_fu_176 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_14_fu_180 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_F) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_15_fu_184 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_D) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_1_fu_128 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_C) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_2_fu_132 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_B) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_3_fu_136 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_A) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_4_fu_140 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_9) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_5_fu_144 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_8) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_6_fu_148 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_7_fu_152 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_8_fu_156 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_9_fu_160 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln60_reg_626 = ap_const_lv4_E) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                block_fu_124 <= m_axi_DATA_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln58_fu_349_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln60_reg_626 <= trunc_ln60_fu_361_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_DATA_ARREADY, icmp_ln58_fu_349_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((m_axi_DATA_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln58_fu_349_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln58_fu_349_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;

    DATA_blk_n_AR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_DATA_ARREADY)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            DATA_blk_n_AR <= m_axi_DATA_ARREADY;
        else 
            DATA_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    DATA_blk_n_R_assign_proc : process(m_axi_DATA_RVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            DATA_blk_n_R <= m_axi_DATA_RVALID;
        else 
            DATA_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    add_ln58_fu_355_p2 <= std_logic_vector(unsigned(i_fu_120) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(8);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, m_axi_DATA_ARREADY)
    begin
        if (((m_axi_DATA_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(m_axi_DATA_RVALID, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_DATA_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(m_axi_DATA_RVALID, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_DATA_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state8_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter1_assign_proc : process(m_axi_DATA_RVALID)
    begin
                ap_block_state9_pp0_stage0_iter1 <= (m_axi_DATA_RVALID = ap_const_logic_0);
    end process;


    ap_condition_pp0_exit_iter0_state8_assign_proc : process(icmp_ln58_fu_349_p2)
    begin
        if ((icmp_ln58_fu_349_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    block_10_out <= block_10_fu_164;

    block_10_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_10_out_ap_vld <= ap_const_logic_1;
        else 
            block_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_11_out <= block_11_fu_168;

    block_11_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_11_out_ap_vld <= ap_const_logic_1;
        else 
            block_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_12_out <= block_12_fu_172;

    block_12_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_12_out_ap_vld <= ap_const_logic_1;
        else 
            block_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_13_out <= block_13_fu_176;

    block_13_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_13_out_ap_vld <= ap_const_logic_1;
        else 
            block_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_14_out <= block_14_fu_180;

    block_14_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_14_out_ap_vld <= ap_const_logic_1;
        else 
            block_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_15_out <= block_15_fu_184;

    block_15_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_15_out_ap_vld <= ap_const_logic_1;
        else 
            block_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_1_out <= block_1_fu_128;

    block_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_1_out_ap_vld <= ap_const_logic_1;
        else 
            block_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_2_out <= block_2_fu_132;

    block_2_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_2_out_ap_vld <= ap_const_logic_1;
        else 
            block_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_3_out <= block_3_fu_136;

    block_3_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_3_out_ap_vld <= ap_const_logic_1;
        else 
            block_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_4_out <= block_4_fu_140;

    block_4_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_4_out_ap_vld <= ap_const_logic_1;
        else 
            block_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_5_out <= block_5_fu_144;

    block_5_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_5_out_ap_vld <= ap_const_logic_1;
        else 
            block_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_6_out <= block_6_fu_148;

    block_6_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_6_out_ap_vld <= ap_const_logic_1;
        else 
            block_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_7_out <= block_7_fu_152;

    block_7_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_7_out_ap_vld <= ap_const_logic_1;
        else 
            block_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_8_out <= block_8_fu_156;

    block_8_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_8_out_ap_vld <= ap_const_logic_1;
        else 
            block_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_9_out <= block_9_fu_160;

    block_9_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_9_out_ap_vld <= ap_const_logic_1;
        else 
            block_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    block_out <= block_fu_124;

    block_out_ap_vld_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            block_out_ap_vld <= ap_const_logic_1;
        else 
            block_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln58_fu_349_p2 <= "1" when (i_fu_120 = ap_const_lv5_10) else "0";
    m_axi_DATA_ARADDR <= sext_ln60_cast_fu_330_p1;
    m_axi_DATA_ARBURST <= ap_const_lv2_0;
    m_axi_DATA_ARCACHE <= ap_const_lv4_0;
    m_axi_DATA_ARID <= ap_const_lv1_0;
    m_axi_DATA_ARLEN <= ap_const_lv32_10;
    m_axi_DATA_ARLOCK <= ap_const_lv2_0;
    m_axi_DATA_ARPROT <= ap_const_lv3_0;
    m_axi_DATA_ARQOS <= ap_const_lv4_0;
    m_axi_DATA_ARREGION <= ap_const_lv4_0;
    m_axi_DATA_ARSIZE <= ap_const_lv3_0;
    m_axi_DATA_ARUSER <= ap_const_lv1_0;

    m_axi_DATA_ARVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_DATA_ARREADY)
    begin
        if ((not(((m_axi_DATA_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_DATA_ARVALID <= ap_const_logic_1;
        else 
            m_axi_DATA_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_DATA_AWADDR <= ap_const_lv64_0;
    m_axi_DATA_AWBURST <= ap_const_lv2_0;
    m_axi_DATA_AWCACHE <= ap_const_lv4_0;
    m_axi_DATA_AWID <= ap_const_lv1_0;
    m_axi_DATA_AWLEN <= ap_const_lv32_0;
    m_axi_DATA_AWLOCK <= ap_const_lv2_0;
    m_axi_DATA_AWPROT <= ap_const_lv3_0;
    m_axi_DATA_AWQOS <= ap_const_lv4_0;
    m_axi_DATA_AWREGION <= ap_const_lv4_0;
    m_axi_DATA_AWSIZE <= ap_const_lv3_0;
    m_axi_DATA_AWUSER <= ap_const_lv1_0;
    m_axi_DATA_AWVALID <= ap_const_logic_0;
    m_axi_DATA_BREADY <= ap_const_logic_0;

    m_axi_DATA_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            m_axi_DATA_RREADY <= ap_const_logic_1;
        else 
            m_axi_DATA_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_DATA_WDATA <= ap_const_lv32_0;
    m_axi_DATA_WID <= ap_const_lv1_0;
    m_axi_DATA_WLAST <= ap_const_logic_0;
    m_axi_DATA_WSTRB <= ap_const_lv4_0;
    m_axi_DATA_WUSER <= ap_const_lv1_0;
    m_axi_DATA_WVALID <= ap_const_logic_0;
        sext_ln60_cast_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln60),64));

    trunc_ln60_fu_361_p1 <= i_fu_120(4 - 1 downto 0);
end behav;
