// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accel_top_maxpool_2x2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_0_address0,
        input_0_0_ce0,
        input_0_0_q0,
        input_0_1_address0,
        input_0_1_ce0,
        input_0_1_q0,
        input_1_0_address0,
        input_1_0_ce0,
        input_1_0_q0,
        input_1_1_address0,
        input_1_1_ce0,
        input_1_1_q0,
        output_r_address1,
        output_r_ce1,
        output_r_we1,
        output_r_d1,
        in_height,
        in_width
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] input_0_0_address0;
output   input_0_0_ce0;
input  [31:0] input_0_0_q0;
output  [7:0] input_0_1_address0;
output   input_0_1_ce0;
input  [31:0] input_0_1_q0;
output  [7:0] input_1_0_address0;
output   input_1_0_ce0;
input  [31:0] input_1_0_q0;
output  [7:0] input_1_1_address0;
output   input_1_1_ce0;
input  [31:0] input_1_1_q0;
output  [9:0] output_r_address1;
output   output_r_ce1;
output   output_r_we1;
output  [31:0] output_r_d1;
input  [31:0] in_height;
input  [31:0] in_width;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] out_height_fu_112_p3;
reg   [31:0] out_height_reg_189;
wire   [31:0] out_width_fu_168_p3;
reg   [31:0] out_width_reg_194;
wire   [63:0] bound_fu_182_p2;
reg   [63:0] bound_reg_200;
wire    ap_CS_fsm_state2;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_idle;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_ready;
wire   [7:0] grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_address0;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_ce0;
wire   [7:0] grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_address0;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_ce0;
wire   [7:0] grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_address0;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_ce0;
wire   [7:0] grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_address0;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_ce0;
wire   [9:0] grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_address1;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_ce1;
wire    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_we1;
wire   [31:0] grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_d1;
reg    grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [31:0] sub_ln22_fu_72_p2;
wire   [30:0] lshr_ln22_1_fu_78_p4;
wire   [31:0] zext_ln22_fu_88_p1;
wire   [30:0] lshr_ln22_2_fu_98_p4;
wire   [0:0] tmp_fu_64_p3;
wire   [31:0] sub_ln22_1_fu_92_p2;
wire   [31:0] zext_ln22_1_fu_108_p1;
wire   [31:0] sub_ln23_fu_128_p2;
wire   [30:0] lshr_ln23_1_fu_134_p4;
wire   [31:0] zext_ln23_fu_144_p1;
wire   [30:0] lshr_ln23_2_fu_154_p4;
wire   [0:0] tmp_4_fu_120_p3;
wire   [31:0] sub_ln23_1_fu_148_p2;
wire   [31:0] zext_ln23_1_fu_164_p1;
wire   [31:0] bound_fu_182_p0;
wire   [31:0] bound_fu_182_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire   [63:0] bound_fu_182_p00;
wire   [63:0] bound_fu_182_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg = 1'b0;
end

accel_top_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start),
    .ap_done(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done),
    .ap_idle(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_idle),
    .ap_ready(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_ready),
    .out_width(out_width_reg_194),
    .bound(bound_reg_200),
    .input_0_0_address0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_address0),
    .input_0_0_ce0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_ce0),
    .input_0_0_q0(input_0_0_q0),
    .input_0_1_address0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_address0),
    .input_0_1_ce0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_ce0),
    .input_0_1_q0(input_0_1_q0),
    .input_1_0_address0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_address0),
    .input_1_0_ce0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_ce0),
    .input_1_0_q0(input_1_0_q0),
    .input_1_1_address0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_address0),
    .input_1_1_ce0(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_ce0),
    .input_1_1_q0(input_1_1_q0),
    .output_r_address1(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_address1),
    .output_r_ce1(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_ce1),
    .output_r_we1(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_we1),
    .output_r_d1(grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_d1)
);

accel_top_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U83(
    .din0(bound_fu_182_p0),
    .din1(bound_fu_182_p1),
    .dout(bound_fu_182_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_ready == 1'b1)) begin
            grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_200 <= bound_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        out_height_reg_189 <= out_height_fu_112_p3;
        out_width_reg_194 <= out_width_fu_168_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign bound_fu_182_p0 = bound_fu_182_p00;

assign bound_fu_182_p00 = out_height_reg_189;

assign bound_fu_182_p1 = bound_fu_182_p10;

assign bound_fu_182_p10 = out_width_reg_194;

assign grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_ap_start_reg;

assign input_0_0_address0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_address0;

assign input_0_0_ce0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_0_ce0;

assign input_0_1_address0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_address0;

assign input_0_1_ce0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_0_1_ce0;

assign input_1_0_address0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_address0;

assign input_1_0_ce0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_0_ce0;

assign input_1_1_address0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_address0;

assign input_1_1_ce0 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_input_1_1_ce0;

assign lshr_ln22_1_fu_78_p4 = {{sub_ln22_fu_72_p2[31:1]}};

assign lshr_ln22_2_fu_98_p4 = {{in_height[31:1]}};

assign lshr_ln23_1_fu_134_p4 = {{sub_ln23_fu_128_p2[31:1]}};

assign lshr_ln23_2_fu_154_p4 = {{in_width[31:1]}};

assign out_height_fu_112_p3 = ((tmp_fu_64_p3[0:0] == 1'b1) ? sub_ln22_1_fu_92_p2 : zext_ln22_1_fu_108_p1);

assign out_width_fu_168_p3 = ((tmp_4_fu_120_p3[0:0] == 1'b1) ? sub_ln23_1_fu_148_p2 : zext_ln23_1_fu_164_p1);

assign output_r_address1 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_address1;

assign output_r_ce1 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_ce1;

assign output_r_d1 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_d1;

assign output_r_we1 = grp_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL_fu_48_output_r_we1;

assign sub_ln22_1_fu_92_p2 = (32'd0 - zext_ln22_fu_88_p1);

assign sub_ln22_fu_72_p2 = (32'd0 - in_height);

assign sub_ln23_1_fu_148_p2 = (32'd0 - zext_ln23_fu_144_p1);

assign sub_ln23_fu_128_p2 = (32'd0 - in_width);

assign tmp_4_fu_120_p3 = in_width[32'd31];

assign tmp_fu_64_p3 = in_height[32'd31];

assign zext_ln22_1_fu_108_p1 = lshr_ln22_2_fu_98_p4;

assign zext_ln22_fu_88_p1 = lshr_ln22_1_fu_78_p4;

assign zext_ln23_1_fu_164_p1 = lshr_ln23_2_fu_154_p4;

assign zext_ln23_fu_144_p1 = lshr_ln23_1_fu_134_p4;

endmodule //accel_top_maxpool_2x2
