// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accel_top_accel_top_Pipeline_STORE_W (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_DATA_AWVALID,
        m_axi_DATA_AWREADY,
        m_axi_DATA_AWADDR,
        m_axi_DATA_AWID,
        m_axi_DATA_AWLEN,
        m_axi_DATA_AWSIZE,
        m_axi_DATA_AWBURST,
        m_axi_DATA_AWLOCK,
        m_axi_DATA_AWCACHE,
        m_axi_DATA_AWPROT,
        m_axi_DATA_AWQOS,
        m_axi_DATA_AWREGION,
        m_axi_DATA_AWUSER,
        m_axi_DATA_WVALID,
        m_axi_DATA_WREADY,
        m_axi_DATA_WDATA,
        m_axi_DATA_WSTRB,
        m_axi_DATA_WLAST,
        m_axi_DATA_WID,
        m_axi_DATA_WUSER,
        m_axi_DATA_ARVALID,
        m_axi_DATA_ARREADY,
        m_axi_DATA_ARADDR,
        m_axi_DATA_ARID,
        m_axi_DATA_ARLEN,
        m_axi_DATA_ARSIZE,
        m_axi_DATA_ARBURST,
        m_axi_DATA_ARLOCK,
        m_axi_DATA_ARCACHE,
        m_axi_DATA_ARPROT,
        m_axi_DATA_ARQOS,
        m_axi_DATA_ARREGION,
        m_axi_DATA_ARUSER,
        m_axi_DATA_RVALID,
        m_axi_DATA_RREADY,
        m_axi_DATA_RDATA,
        m_axi_DATA_RLAST,
        m_axi_DATA_RID,
        m_axi_DATA_RFIFONUM,
        m_axi_DATA_RUSER,
        m_axi_DATA_RRESP,
        m_axi_DATA_BVALID,
        m_axi_DATA_BREADY,
        m_axi_DATA_BRESP,
        m_axi_DATA_BID,
        m_axi_DATA_BUSER,
        sext_ln166_1,
        final_width,
        zext_ln164,
        pool_output_V_address0,
        pool_output_V_ce0,
        pool_output_V_q0,
        output_data,
        zext_ln166_1,
        conv_output_V_address0,
        conv_output_V_ce0,
        conv_output_V_q0,
        conv_output_V_1_address0,
        conv_output_V_1_ce0,
        conv_output_V_1_q0,
        conv_output_V_2_address0,
        conv_output_V_2_ce0,
        conv_output_V_2_q0,
        conv_output_V_3_address0,
        conv_output_V_3_ce0,
        conv_output_V_3_q0,
        trunc_ln160_1,
        icmp_ln104
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_DATA_AWVALID;
input   m_axi_DATA_AWREADY;
output  [63:0] m_axi_DATA_AWADDR;
output  [0:0] m_axi_DATA_AWID;
output  [31:0] m_axi_DATA_AWLEN;
output  [2:0] m_axi_DATA_AWSIZE;
output  [1:0] m_axi_DATA_AWBURST;
output  [1:0] m_axi_DATA_AWLOCK;
output  [3:0] m_axi_DATA_AWCACHE;
output  [2:0] m_axi_DATA_AWPROT;
output  [3:0] m_axi_DATA_AWQOS;
output  [3:0] m_axi_DATA_AWREGION;
output  [0:0] m_axi_DATA_AWUSER;
output   m_axi_DATA_WVALID;
input   m_axi_DATA_WREADY;
output  [31:0] m_axi_DATA_WDATA;
output  [3:0] m_axi_DATA_WSTRB;
output   m_axi_DATA_WLAST;
output  [0:0] m_axi_DATA_WID;
output  [0:0] m_axi_DATA_WUSER;
output   m_axi_DATA_ARVALID;
input   m_axi_DATA_ARREADY;
output  [63:0] m_axi_DATA_ARADDR;
output  [0:0] m_axi_DATA_ARID;
output  [31:0] m_axi_DATA_ARLEN;
output  [2:0] m_axi_DATA_ARSIZE;
output  [1:0] m_axi_DATA_ARBURST;
output  [1:0] m_axi_DATA_ARLOCK;
output  [3:0] m_axi_DATA_ARCACHE;
output  [2:0] m_axi_DATA_ARPROT;
output  [3:0] m_axi_DATA_ARQOS;
output  [3:0] m_axi_DATA_ARREGION;
output  [0:0] m_axi_DATA_ARUSER;
input   m_axi_DATA_RVALID;
output   m_axi_DATA_RREADY;
input  [31:0] m_axi_DATA_RDATA;
input   m_axi_DATA_RLAST;
input  [0:0] m_axi_DATA_RID;
input  [8:0] m_axi_DATA_RFIFONUM;
input  [0:0] m_axi_DATA_RUSER;
input  [1:0] m_axi_DATA_RRESP;
input   m_axi_DATA_BVALID;
output   m_axi_DATA_BREADY;
input  [1:0] m_axi_DATA_BRESP;
input  [0:0] m_axi_DATA_BID;
input  [0:0] m_axi_DATA_BUSER;
input  [31:0] sext_ln166_1;
input  [30:0] final_width;
input  [9:0] zext_ln164;
output  [9:0] pool_output_V_address0;
output   pool_output_V_ce0;
input  [31:0] pool_output_V_q0;
input  [63:0] output_data;
input  [7:0] zext_ln166_1;
output  [7:0] conv_output_V_address0;
output   conv_output_V_ce0;
input  [31:0] conv_output_V_q0;
output  [7:0] conv_output_V_1_address0;
output   conv_output_V_1_ce0;
input  [31:0] conv_output_V_1_q0;
output  [7:0] conv_output_V_2_address0;
output   conv_output_V_2_ce0;
input  [31:0] conv_output_V_2_q0;
output  [7:0] conv_output_V_3_address0;
output   conv_output_V_3_ce0;
input  [31:0] conv_output_V_3_q0;
input  [0:0] trunc_ln160_1;
input  [0:0] icmp_ln104;

reg ap_idle;
reg m_axi_DATA_AWVALID;
reg m_axi_DATA_WVALID;
reg m_axi_DATA_BREADY;
reg pool_output_V_ce0;
reg conv_output_V_ce0;
reg conv_output_V_1_ce0;
reg conv_output_V_2_ce0;
reg conv_output_V_3_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln161_fu_258_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    DATA_blk_n_AW;
wire    ap_block_pp0_stage0;
reg    DATA_blk_n_W;
reg    DATA_blk_n_B;
wire   [0:0] icmp_ln104_read_reg_414;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln161_fu_286_p1;
reg   [0:0] trunc_ln161_reg_453;
reg   [63:0] DATA_addr_reg_459;
wire   [31:0] select_ln104_fu_393_p3;
reg   [31:0] select_ln104_reg_485;
wire   [63:0] zext_ln164_1_fu_281_p1;
wire   [63:0] zext_ln166_fu_348_p1;
wire  signed [63:0] sext_ln166_fu_323_p1;
reg    ap_block_pp0_stage0_01001;
reg   [30:0] w_fu_110;
wire   [30:0] add_ln161_fu_263_p2;
wire    ap_loop_init;
reg   [32:0] out_ptr_fu_114;
wire   [32:0] add_ln166_fu_290_p2;
wire  signed [32:0] sext_ln166_1_cast_fu_241_p1;
wire   [9:0] trunc_ln164_fu_272_p1;
wire   [9:0] add_ln164_fu_276_p2;
wire   [34:0] shl_ln4_fu_296_p3;
wire  signed [63:0] sext_ln166_2_fu_304_p1;
wire   [63:0] add_ln166_1_fu_308_p2;
wire   [61:0] trunc_ln8_fu_313_p4;
wire   [7:0] lshr_ln166_1_fu_333_p4;
wire   [7:0] add_ln166_2_fu_343_p2;
wire   [31:0] tmp_fu_366_p4;
wire   [31:0] tmp_s_fu_375_p4;
wire   [31:0] tmp_1_fu_384_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

accel_top_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U91(
    .din0(conv_output_V_q0),
    .din1(conv_output_V_1_q0),
    .din2(trunc_ln161_reg_453),
    .dout(tmp_fu_366_p4)
);

accel_top_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U92(
    .din0(conv_output_V_2_q0),
    .din1(conv_output_V_3_q0),
    .din2(trunc_ln161_reg_453),
    .dout(tmp_s_fu_375_p4)
);

accel_top_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U93(
    .din0(tmp_fu_366_p4),
    .din1(tmp_s_fu_375_p4),
    .din2(trunc_ln160_1),
    .dout(tmp_1_fu_384_p4)
);

accel_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_ptr_fu_114 <= sext_ln166_1_cast_fu_241_p1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln161_fu_258_p2 == 1'd0))) begin
            out_ptr_fu_114 <= add_ln166_fu_290_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_110 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln161_fu_258_p2 == 1'd0))) begin
            w_fu_110 <= add_ln161_fu_263_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln161_fu_258_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        DATA_addr_reg_459 <= sext_ln166_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        select_ln104_reg_485 <= select_ln104_fu_393_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln104_read_reg_414 == 1'd0) & (icmp_ln161_fu_258_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln161_reg_453 <= trunc_ln161_fu_286_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        DATA_blk_n_AW = m_axi_DATA_AWREADY;
    end else begin
        DATA_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        DATA_blk_n_B = m_axi_DATA_BVALID;
    end else begin
        DATA_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        DATA_blk_n_W = m_axi_DATA_WREADY;
    end else begin
        DATA_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln161_fu_258_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv_output_V_1_ce0 = 1'b1;
    end else begin
        conv_output_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv_output_V_2_ce0 = 1'b1;
    end else begin
        conv_output_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv_output_V_3_ce0 = 1'b1;
    end else begin
        conv_output_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv_output_V_ce0 = 1'b1;
    end else begin
        conv_output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_DATA_AWVALID = 1'b1;
    end else begin
        m_axi_DATA_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_DATA_BREADY = 1'b1;
    end else begin
        m_axi_DATA_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_DATA_WVALID = 1'b1;
    end else begin
        m_axi_DATA_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pool_output_V_ce0 = 1'b1;
    end else begin
        pool_output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln161_fu_263_p2 = (w_fu_110 + 31'd1);

assign add_ln164_fu_276_p2 = (zext_ln164 + trunc_ln164_fu_272_p1);

assign add_ln166_1_fu_308_p2 = ($signed(sext_ln166_2_fu_304_p1) + $signed(output_data));

assign add_ln166_2_fu_343_p2 = (zext_ln166_1 + lshr_ln166_1_fu_333_p4);

assign add_ln166_fu_290_p2 = (out_ptr_fu_114 + 33'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((m_axi_DATA_BVALID == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_DATA_BVALID == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((m_axi_DATA_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((m_axi_DATA_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_DATA_BVALID == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((m_axi_DATA_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((m_axi_DATA_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (m_axi_DATA_BVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign conv_output_V_1_address0 = zext_ln166_fu_348_p1;

assign conv_output_V_2_address0 = zext_ln166_fu_348_p1;

assign conv_output_V_3_address0 = zext_ln166_fu_348_p1;

assign conv_output_V_address0 = zext_ln166_fu_348_p1;

assign icmp_ln104_read_reg_414 = icmp_ln104;

assign icmp_ln161_fu_258_p2 = ((w_fu_110 == final_width) ? 1'b1 : 1'b0);

assign lshr_ln166_1_fu_333_p4 = {{w_fu_110[8:1]}};

assign m_axi_DATA_ARADDR = 64'd0;

assign m_axi_DATA_ARBURST = 2'd0;

assign m_axi_DATA_ARCACHE = 4'd0;

assign m_axi_DATA_ARID = 1'd0;

assign m_axi_DATA_ARLEN = 32'd0;

assign m_axi_DATA_ARLOCK = 2'd0;

assign m_axi_DATA_ARPROT = 3'd0;

assign m_axi_DATA_ARQOS = 4'd0;

assign m_axi_DATA_ARREGION = 4'd0;

assign m_axi_DATA_ARSIZE = 3'd0;

assign m_axi_DATA_ARUSER = 1'd0;

assign m_axi_DATA_ARVALID = 1'b0;

assign m_axi_DATA_AWADDR = DATA_addr_reg_459;

assign m_axi_DATA_AWBURST = 2'd0;

assign m_axi_DATA_AWCACHE = 4'd0;

assign m_axi_DATA_AWID = 1'd0;

assign m_axi_DATA_AWLEN = 32'd1;

assign m_axi_DATA_AWLOCK = 2'd0;

assign m_axi_DATA_AWPROT = 3'd0;

assign m_axi_DATA_AWQOS = 4'd0;

assign m_axi_DATA_AWREGION = 4'd0;

assign m_axi_DATA_AWSIZE = 3'd0;

assign m_axi_DATA_AWUSER = 1'd0;

assign m_axi_DATA_RREADY = 1'b0;

assign m_axi_DATA_WDATA = select_ln104_reg_485;

assign m_axi_DATA_WID = 1'd0;

assign m_axi_DATA_WLAST = 1'b0;

assign m_axi_DATA_WSTRB = 4'd15;

assign m_axi_DATA_WUSER = 1'd0;

assign pool_output_V_address0 = zext_ln164_1_fu_281_p1;

assign select_ln104_fu_393_p3 = ((icmp_ln104[0:0] == 1'b1) ? pool_output_V_q0 : tmp_1_fu_384_p4);

assign sext_ln166_1_cast_fu_241_p1 = $signed(sext_ln166_1);

assign sext_ln166_2_fu_304_p1 = $signed(shl_ln4_fu_296_p3);

assign sext_ln166_fu_323_p1 = $signed(trunc_ln8_fu_313_p4);

assign shl_ln4_fu_296_p3 = {{out_ptr_fu_114}, {2'd0}};

assign trunc_ln161_fu_286_p1 = w_fu_110[0:0];

assign trunc_ln164_fu_272_p1 = w_fu_110[9:0];

assign trunc_ln8_fu_313_p4 = {{add_ln166_1_fu_308_p2[63:2]}};

assign zext_ln164_1_fu_281_p1 = add_ln164_fu_276_p2;

assign zext_ln166_fu_348_p1 = add_ln166_2_fu_343_p2;

endmodule //accel_top_accel_top_Pipeline_STORE_W
