// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_top_sha256_top_Pipeline_LOAD_BLOCK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_DATA_AWVALID,
        m_axi_DATA_AWREADY,
        m_axi_DATA_AWADDR,
        m_axi_DATA_AWID,
        m_axi_DATA_AWLEN,
        m_axi_DATA_AWSIZE,
        m_axi_DATA_AWBURST,
        m_axi_DATA_AWLOCK,
        m_axi_DATA_AWCACHE,
        m_axi_DATA_AWPROT,
        m_axi_DATA_AWQOS,
        m_axi_DATA_AWREGION,
        m_axi_DATA_AWUSER,
        m_axi_DATA_WVALID,
        m_axi_DATA_WREADY,
        m_axi_DATA_WDATA,
        m_axi_DATA_WSTRB,
        m_axi_DATA_WLAST,
        m_axi_DATA_WID,
        m_axi_DATA_WUSER,
        m_axi_DATA_ARVALID,
        m_axi_DATA_ARREADY,
        m_axi_DATA_ARADDR,
        m_axi_DATA_ARID,
        m_axi_DATA_ARLEN,
        m_axi_DATA_ARSIZE,
        m_axi_DATA_ARBURST,
        m_axi_DATA_ARLOCK,
        m_axi_DATA_ARCACHE,
        m_axi_DATA_ARPROT,
        m_axi_DATA_ARQOS,
        m_axi_DATA_ARREGION,
        m_axi_DATA_ARUSER,
        m_axi_DATA_RVALID,
        m_axi_DATA_RREADY,
        m_axi_DATA_RDATA,
        m_axi_DATA_RLAST,
        m_axi_DATA_RID,
        m_axi_DATA_RFIFONUM,
        m_axi_DATA_RUSER,
        m_axi_DATA_RRESP,
        m_axi_DATA_BVALID,
        m_axi_DATA_BREADY,
        m_axi_DATA_BRESP,
        m_axi_DATA_BID,
        m_axi_DATA_BUSER,
        sext_ln60,
        sext_ln52,
        zext_ln52,
        block_15_out,
        block_15_out_ap_vld,
        block_14_out,
        block_14_out_ap_vld,
        block_13_out,
        block_13_out_ap_vld,
        block_12_out,
        block_12_out_ap_vld,
        block_11_out,
        block_11_out_ap_vld,
        block_10_out,
        block_10_out_ap_vld,
        block_9_out,
        block_9_out_ap_vld,
        block_8_out,
        block_8_out_ap_vld,
        block_7_out,
        block_7_out_ap_vld,
        block_6_out,
        block_6_out_ap_vld,
        block_5_out,
        block_5_out_ap_vld,
        block_4_out,
        block_4_out_ap_vld,
        block_3_out,
        block_3_out_ap_vld,
        block_2_out,
        block_2_out_ap_vld,
        block_1_out,
        block_1_out_ap_vld,
        block_out,
        block_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_pp0_stage0 = 9'd128;
parameter    ap_ST_fsm_state10 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_DATA_AWVALID;
input   m_axi_DATA_AWREADY;
output  [63:0] m_axi_DATA_AWADDR;
output  [0:0] m_axi_DATA_AWID;
output  [31:0] m_axi_DATA_AWLEN;
output  [2:0] m_axi_DATA_AWSIZE;
output  [1:0] m_axi_DATA_AWBURST;
output  [1:0] m_axi_DATA_AWLOCK;
output  [3:0] m_axi_DATA_AWCACHE;
output  [2:0] m_axi_DATA_AWPROT;
output  [3:0] m_axi_DATA_AWQOS;
output  [3:0] m_axi_DATA_AWREGION;
output  [0:0] m_axi_DATA_AWUSER;
output   m_axi_DATA_WVALID;
input   m_axi_DATA_WREADY;
output  [31:0] m_axi_DATA_WDATA;
output  [3:0] m_axi_DATA_WSTRB;
output   m_axi_DATA_WLAST;
output  [0:0] m_axi_DATA_WID;
output  [0:0] m_axi_DATA_WUSER;
output   m_axi_DATA_ARVALID;
input   m_axi_DATA_ARREADY;
output  [63:0] m_axi_DATA_ARADDR;
output  [0:0] m_axi_DATA_ARID;
output  [31:0] m_axi_DATA_ARLEN;
output  [2:0] m_axi_DATA_ARSIZE;
output  [1:0] m_axi_DATA_ARBURST;
output  [1:0] m_axi_DATA_ARLOCK;
output  [3:0] m_axi_DATA_ARCACHE;
output  [2:0] m_axi_DATA_ARPROT;
output  [3:0] m_axi_DATA_ARQOS;
output  [3:0] m_axi_DATA_ARREGION;
output  [0:0] m_axi_DATA_ARUSER;
input   m_axi_DATA_RVALID;
output   m_axi_DATA_RREADY;
input  [31:0] m_axi_DATA_RDATA;
input   m_axi_DATA_RLAST;
input  [0:0] m_axi_DATA_RID;
input  [8:0] m_axi_DATA_RFIFONUM;
input  [0:0] m_axi_DATA_RUSER;
input  [1:0] m_axi_DATA_RRESP;
input   m_axi_DATA_BVALID;
output   m_axi_DATA_BREADY;
input  [1:0] m_axi_DATA_BRESP;
input  [0:0] m_axi_DATA_BID;
input  [0:0] m_axi_DATA_BUSER;
input  [62:0] sext_ln60;
input  [61:0] sext_ln52;
input  [31:0] zext_ln52;
output  [31:0] block_15_out;
output   block_15_out_ap_vld;
output  [31:0] block_14_out;
output   block_14_out_ap_vld;
output  [31:0] block_13_out;
output   block_13_out_ap_vld;
output  [31:0] block_12_out;
output   block_12_out_ap_vld;
output  [31:0] block_11_out;
output   block_11_out_ap_vld;
output  [31:0] block_10_out;
output   block_10_out_ap_vld;
output  [31:0] block_9_out;
output   block_9_out_ap_vld;
output  [31:0] block_8_out;
output   block_8_out_ap_vld;
output  [31:0] block_7_out;
output   block_7_out_ap_vld;
output  [31:0] block_6_out;
output   block_6_out_ap_vld;
output  [31:0] block_5_out;
output   block_5_out_ap_vld;
output  [31:0] block_4_out;
output   block_4_out_ap_vld;
output  [31:0] block_3_out;
output   block_3_out_ap_vld;
output  [31:0] block_2_out;
output   block_2_out_ap_vld;
output  [31:0] block_1_out;
output   block_1_out_ap_vld;
output  [31:0] block_out;
output   block_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_DATA_ARVALID;
reg m_axi_DATA_RREADY;
reg block_15_out_ap_vld;
reg block_14_out_ap_vld;
reg block_13_out_ap_vld;
reg block_12_out_ap_vld;
reg block_11_out_ap_vld;
reg block_10_out_ap_vld;
reg block_9_out_ap_vld;
reg block_8_out_ap_vld;
reg block_7_out_ap_vld;
reg block_6_out_ap_vld;
reg block_5_out_ap_vld;
reg block_4_out_ap_vld;
reg block_3_out_ap_vld;
reg block_2_out_ap_vld;
reg block_1_out_ap_vld;
reg block_out_ap_vld;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    DATA_blk_n_AR;
reg    DATA_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
wire   [3:0] trunc_ln60_fu_361_p1;
reg   [3:0] trunc_ln60_reg_626;
wire    ap_block_state8_pp0_stage0_iter0;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln58_fu_349_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state7;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
wire  signed [63:0] sext_ln60_cast_fu_330_p1;
reg   [4:0] i_fu_120;
wire   [4:0] add_ln58_fu_355_p2;
reg   [31:0] block_fu_124;
wire    ap_CS_fsm_state10;
reg   [31:0] block_1_fu_128;
reg   [31:0] block_2_fu_132;
reg   [31:0] block_3_fu_136;
reg   [31:0] block_4_fu_140;
reg   [31:0] block_5_fu_144;
reg   [31:0] block_6_fu_148;
reg   [31:0] block_7_fu_152;
reg   [31:0] block_8_fu_156;
reg   [31:0] block_9_fu_160;
reg   [31:0] block_10_fu_164;
reg   [31:0] block_11_fu_168;
reg   [31:0] block_12_fu_172;
reg   [31:0] block_13_fu_176;
reg   [31:0] block_14_fu_180;
reg   [31:0] block_15_fu_184;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state8);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_DATA_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_120 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln58_fu_349_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_fu_120 <= add_ln58_fu_355_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_10_fu_164 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_11_fu_168 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_12_fu_172 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_13_fu_176 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_14_fu_180 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_15_fu_184 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_1_fu_128 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_2_fu_132 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_3_fu_136 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_4_fu_140 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_5_fu_144 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_6_fu_148 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_7_fu_152 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_8_fu_156 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_9_fu_160 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_626 == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        block_fu_124 <= m_axi_DATA_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln58_fu_349_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln60_reg_626 <= trunc_ln60_fu_361_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        DATA_blk_n_AR = m_axi_DATA_ARREADY;
    end else begin
        DATA_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        DATA_blk_n_R = m_axi_DATA_RVALID;
    end else begin
        DATA_blk_n_R = 1'b1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if (((m_axi_DATA_ARREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln58_fu_349_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_10_out_ap_vld = 1'b1;
    end else begin
        block_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_11_out_ap_vld = 1'b1;
    end else begin
        block_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_12_out_ap_vld = 1'b1;
    end else begin
        block_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_13_out_ap_vld = 1'b1;
    end else begin
        block_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_14_out_ap_vld = 1'b1;
    end else begin
        block_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_15_out_ap_vld = 1'b1;
    end else begin
        block_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_1_out_ap_vld = 1'b1;
    end else begin
        block_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_2_out_ap_vld = 1'b1;
    end else begin
        block_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_3_out_ap_vld = 1'b1;
    end else begin
        block_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_4_out_ap_vld = 1'b1;
    end else begin
        block_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_5_out_ap_vld = 1'b1;
    end else begin
        block_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_6_out_ap_vld = 1'b1;
    end else begin
        block_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_7_out_ap_vld = 1'b1;
    end else begin
        block_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_8_out_ap_vld = 1'b1;
    end else begin
        block_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_9_out_ap_vld = 1'b1;
    end else begin
        block_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        block_out_ap_vld = 1'b1;
    end else begin
        block_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_DATA_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_DATA_ARVALID = 1'b1;
    end else begin
        m_axi_DATA_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        m_axi_DATA_RREADY = 1'b1;
    end else begin
        m_axi_DATA_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_DATA_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln58_fu_349_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln58_fu_349_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_fu_355_p2 = (i_fu_120 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_DATA_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_DATA_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = (m_axi_DATA_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign block_10_out = block_10_fu_164;

assign block_11_out = block_11_fu_168;

assign block_12_out = block_12_fu_172;

assign block_13_out = block_13_fu_176;

assign block_14_out = block_14_fu_180;

assign block_15_out = block_15_fu_184;

assign block_1_out = block_1_fu_128;

assign block_2_out = block_2_fu_132;

assign block_3_out = block_3_fu_136;

assign block_4_out = block_4_fu_140;

assign block_5_out = block_5_fu_144;

assign block_6_out = block_6_fu_148;

assign block_7_out = block_7_fu_152;

assign block_8_out = block_8_fu_156;

assign block_9_out = block_9_fu_160;

assign block_out = block_fu_124;

assign icmp_ln58_fu_349_p2 = ((i_fu_120 == 5'd16) ? 1'b1 : 1'b0);

assign m_axi_DATA_ARADDR = sext_ln60_cast_fu_330_p1;

assign m_axi_DATA_ARBURST = 2'd0;

assign m_axi_DATA_ARCACHE = 4'd0;

assign m_axi_DATA_ARID = 1'd0;

assign m_axi_DATA_ARLEN = 32'd16;

assign m_axi_DATA_ARLOCK = 2'd0;

assign m_axi_DATA_ARPROT = 3'd0;

assign m_axi_DATA_ARQOS = 4'd0;

assign m_axi_DATA_ARREGION = 4'd0;

assign m_axi_DATA_ARSIZE = 3'd0;

assign m_axi_DATA_ARUSER = 1'd0;

assign m_axi_DATA_AWADDR = 64'd0;

assign m_axi_DATA_AWBURST = 2'd0;

assign m_axi_DATA_AWCACHE = 4'd0;

assign m_axi_DATA_AWID = 1'd0;

assign m_axi_DATA_AWLEN = 32'd0;

assign m_axi_DATA_AWLOCK = 2'd0;

assign m_axi_DATA_AWPROT = 3'd0;

assign m_axi_DATA_AWQOS = 4'd0;

assign m_axi_DATA_AWREGION = 4'd0;

assign m_axi_DATA_AWSIZE = 3'd0;

assign m_axi_DATA_AWUSER = 1'd0;

assign m_axi_DATA_AWVALID = 1'b0;

assign m_axi_DATA_BREADY = 1'b0;

assign m_axi_DATA_WDATA = 32'd0;

assign m_axi_DATA_WID = 1'd0;

assign m_axi_DATA_WLAST = 1'b0;

assign m_axi_DATA_WSTRB = 4'd0;

assign m_axi_DATA_WUSER = 1'd0;

assign m_axi_DATA_WVALID = 1'b0;

assign sext_ln60_cast_fu_330_p1 = $signed(sext_ln60);

assign trunc_ln60_fu_361_p1 = i_fu_120[3:0];

endmodule //sha256_top_sha256_top_Pipeline_LOAD_BLOCK
