-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aes128_top_aes128_top_Pipeline_STORE_DATA is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_DATA_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_AWREADY : IN STD_LOGIC;
    m_axi_DATA_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_DATA_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_WVALID : OUT STD_LOGIC;
    m_axi_DATA_WREADY : IN STD_LOGIC;
    m_axi_DATA_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_WLAST : OUT STD_LOGIC;
    m_axi_DATA_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_ARREADY : IN STD_LOGIC;
    m_axi_DATA_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_DATA_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_DATA_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_DATA_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RVALID : IN STD_LOGIC;
    m_axi_DATA_RREADY : OUT STD_LOGIC;
    m_axi_DATA_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_DATA_RLAST : IN STD_LOGIC;
    m_axi_DATA_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_DATA_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_BVALID : IN STD_LOGIC;
    m_axi_DATA_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_DATA_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_DATA_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln77 : IN STD_LOGIC_VECTOR (61 downto 0);
    ciphertext_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ciphertext_ce0 : OUT STD_LOGIC;
    ciphertext_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    ciphertext_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ciphertext_ce1 : OUT STD_LOGIC;
    ciphertext_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    ciphertext_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ciphertext_1_ce0 : OUT STD_LOGIC;
    ciphertext_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    ciphertext_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ciphertext_1_ce1 : OUT STD_LOGIC;
    ciphertext_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of aes128_top_aes128_top_Pipeline_STORE_DATA is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln77_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal DATA_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln77_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal ciphertext_load_reg_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal ciphertext_1_load_reg_237 : STD_LOGIC_VECTOR (7 downto 0);
    signal ciphertext_load_1_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal ciphertext_1_load_1_reg_247 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln79_fu_154_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln81_fu_166_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal i_fu_56 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln77_fu_142_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln79_fu_148_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln81_fu_160_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component aes128_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component aes128_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln77_fu_136_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_56 <= add_ln77_fu_142_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_56 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln77_reg_203 <= icmp_ln77_fu_136_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln77_reg_203 = ap_const_lv1_0))) then
                ciphertext_1_load_1_reg_247 <= ciphertext_1_q0;
                ciphertext_1_load_reg_237 <= ciphertext_1_q1;
                ciphertext_load_1_reg_242 <= ciphertext_q0;
                ciphertext_load_reg_232 <= ciphertext_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    DATA_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_DATA_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            DATA_blk_n_W <= m_axi_DATA_WREADY;
        else 
            DATA_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    add_ln77_fu_142_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_DATA_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_DATA_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_DATA_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_DATA_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln77_fu_136_p2)
    begin
        if (((icmp_ln77_fu_136_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln77_reg_203)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln77_reg_203 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_56, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_56;
        end if; 
    end process;

    ciphertext_1_address0 <= zext_ln81_fu_166_p1(3 - 1 downto 0);
    ciphertext_1_address1 <= zext_ln79_fu_154_p1(3 - 1 downto 0);

    ciphertext_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ciphertext_1_ce0 <= ap_const_logic_1;
        else 
            ciphertext_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ciphertext_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ciphertext_1_ce1 <= ap_const_logic_1;
        else 
            ciphertext_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    ciphertext_address0 <= zext_ln81_fu_166_p1(3 - 1 downto 0);
    ciphertext_address1 <= zext_ln79_fu_154_p1(3 - 1 downto 0);

    ciphertext_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ciphertext_ce0 <= ap_const_logic_1;
        else 
            ciphertext_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ciphertext_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ciphertext_ce1 <= ap_const_logic_1;
        else 
            ciphertext_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln77_fu_136_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv3_4) else "0";
    m_axi_DATA_ARADDR <= ap_const_lv64_0;
    m_axi_DATA_ARBURST <= ap_const_lv2_0;
    m_axi_DATA_ARCACHE <= ap_const_lv4_0;
    m_axi_DATA_ARID <= ap_const_lv1_0;
    m_axi_DATA_ARLEN <= ap_const_lv32_0;
    m_axi_DATA_ARLOCK <= ap_const_lv2_0;
    m_axi_DATA_ARPROT <= ap_const_lv3_0;
    m_axi_DATA_ARQOS <= ap_const_lv4_0;
    m_axi_DATA_ARREGION <= ap_const_lv4_0;
    m_axi_DATA_ARSIZE <= ap_const_lv3_0;
    m_axi_DATA_ARUSER <= ap_const_lv1_0;
    m_axi_DATA_ARVALID <= ap_const_logic_0;
    m_axi_DATA_AWADDR <= ap_const_lv64_0;
    m_axi_DATA_AWBURST <= ap_const_lv2_0;
    m_axi_DATA_AWCACHE <= ap_const_lv4_0;
    m_axi_DATA_AWID <= ap_const_lv1_0;
    m_axi_DATA_AWLEN <= ap_const_lv32_0;
    m_axi_DATA_AWLOCK <= ap_const_lv2_0;
    m_axi_DATA_AWPROT <= ap_const_lv3_0;
    m_axi_DATA_AWQOS <= ap_const_lv4_0;
    m_axi_DATA_AWREGION <= ap_const_lv4_0;
    m_axi_DATA_AWSIZE <= ap_const_lv3_0;
    m_axi_DATA_AWUSER <= ap_const_lv1_0;
    m_axi_DATA_AWVALID <= ap_const_logic_0;
    m_axi_DATA_BREADY <= ap_const_logic_0;
    m_axi_DATA_RREADY <= ap_const_logic_0;
    m_axi_DATA_WDATA <= (((ciphertext_load_reg_232 & ciphertext_1_load_reg_237) & ciphertext_load_1_reg_242) & ciphertext_1_load_1_reg_247);
    m_axi_DATA_WID <= ap_const_lv1_0;
    m_axi_DATA_WLAST <= ap_const_logic_0;
    m_axi_DATA_WSTRB <= ap_const_lv4_F;
    m_axi_DATA_WUSER <= ap_const_lv1_0;

    m_axi_DATA_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_DATA_WVALID <= ap_const_logic_1;
        else 
            m_axi_DATA_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln81_fu_160_p2 <= (shl_ln79_fu_148_p2 or ap_const_lv3_1);
    shl_ln79_fu_148_p2 <= std_logic_vector(shift_left(unsigned(ap_sig_allocacmp_i_2),to_integer(unsigned('0' & ap_const_lv3_1(3-1 downto 0)))));
    zext_ln79_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln79_fu_148_p2),64));
    zext_ln81_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln81_fu_160_p2),64));
end behav;
