-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity accel_top_conv_engine is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    weights_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    weights_ce0 : OUT STD_LOGIC;
    weights_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    bias : IN STD_LOGIC_VECTOR (31 downto 0);
    output_0_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_0_0_ce1 : OUT STD_LOGIC;
    output_0_0_we1 : OUT STD_LOGIC;
    output_0_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_0_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_0_1_ce1 : OUT STD_LOGIC;
    output_0_1_we1 : OUT STD_LOGIC;
    output_0_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_1_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_1_0_ce1 : OUT STD_LOGIC;
    output_1_0_we1 : OUT STD_LOGIC;
    output_1_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_1_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_1_1_ce1 : OUT STD_LOGIC;
    output_1_1_we1 : OUT STD_LOGIC;
    output_1_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    kernel_size : IN STD_LOGIC_VECTOR (31 downto 0);
    in_channels : IN STD_LOGIC_VECTOR (31 downto 0);
    in_height : IN STD_LOGIC_VECTOR (31 downto 0);
    in_width : IN STD_LOGIC_VECTOR (31 downto 0);
    stride : IN STD_LOGIC_VECTOR (31 downto 0);
    padding : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of accel_top_conv_engine is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (41 downto 0) := "000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (41 downto 0) := "000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (41 downto 0) := "000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (41 downto 0) := "000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (41 downto 0) := "000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (41 downto 0) := "000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (41 downto 0) := "000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (41 downto 0) := "000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (41 downto 0) := "000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (41 downto 0) := "001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (41 downto 0) := "010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (41 downto 0) := "100000000000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bound_fu_275_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_557 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state32 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state32 : signal is "none";
    signal ap_CS_fsm_state33 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state33 : signal is "none";
    signal out_height_fu_294_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_height_reg_573 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state36 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state36 : signal is "none";
    signal out_width_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_width_reg_578 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state37 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state37 : signal is "none";
    signal grp_fu_288_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal bound4_reg_589 : STD_LOGIC_VECTOR (95 downto 0);
    signal bound32_fu_312_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound32_reg_594 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln48_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_599 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln36_1_fu_331_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln36_1_reg_607 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal select_ln36_fu_354_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln36_reg_612 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln36_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln36_1_fu_362_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln36_1_reg_618 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln36_fu_388_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln36_reg_624 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln63_fu_402_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln63_reg_628 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln63_fu_408_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln63_reg_633 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln36_fu_412_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_reg_637 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state39 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state39 : signal is "none";
    signal mul_ln40_fu_416_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln40_reg_642 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln36_fu_420_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln36_reg_647 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state40 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state40 : signal is "none";
    signal sub_ln40_fu_425_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln40_reg_652 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln52_3_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_3_reg_657 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start : STD_LOGIC;
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_done : STD_LOGIC;
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_idle : STD_LOGIC;
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_ready : STD_LOGIC;
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_weights_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_weights_ce0 : STD_LOGIC;
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_input_r_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_input_r_ce0 : STD_LOGIC;
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out_ap_vld : STD_LOGIC;
    signal grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state41 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state41 : signal is "none";
    signal zext_ln63_fu_463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state42 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state42 : signal is "none";
    signal ow_fu_70 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln39_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal oh_fu_74 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten34_fu_78 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln33_fu_221_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln33_fu_215_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_233_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln34_fu_239_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_251_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_275_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cast_fu_272_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_275_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_288_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_288_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_233_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_251_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound32_fu_312_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound32_fu_312_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln39_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln36_fu_343_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln63_mid2_v_fu_370_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_380_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln63_1_fu_392_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_233_ap_start : STD_LOGIC;
    signal grp_fu_233_ap_done : STD_LOGIC;
    signal grp_fu_251_ap_start : STD_LOGIC;
    signal grp_fu_251_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (41 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ST_fsm_state39_blk : STD_LOGIC;
    signal ap_ST_fsm_state40_blk : STD_LOGIC;
    signal ap_ST_fsm_state41_blk : STD_LOGIC;
    signal ap_ST_fsm_state42_blk : STD_LOGIC;
    signal bound32_fu_312_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound32_fu_312_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_288_p00 : STD_LOGIC_VECTOR (95 downto 0);
    signal grp_fu_288_p10 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component accel_top_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bias : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln36_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln36_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        bound4 : IN STD_LOGIC_VECTOR (95 downto 0);
        bound : IN STD_LOGIC_VECTOR (63 downto 0);
        and_ln52_3 : IN STD_LOGIC_VECTOR (0 downto 0);
        kernel_size : IN STD_LOGIC_VECTOR (31 downto 0);
        icmp_ln48_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        weights_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        weights_ce0 : OUT STD_LOGIC;
        weights_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln43 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36 : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_V_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component accel_top_sdiv_32ns_32s_32_36_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component accel_top_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component accel_top_mul_32ns_64ns_96_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (95 downto 0) );
    end component;


    component accel_top_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196 : component accel_top_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start,
        ap_done => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_done,
        ap_idle => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_idle,
        ap_ready => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_ready,
        bias => bias,
        sext_ln36_2 => sub_ln36_reg_647,
        sext_ln36_1 => in_height,
        bound4 => bound4_reg_589,
        bound => bound_reg_557,
        and_ln52_3 => and_ln52_3_reg_657,
        kernel_size => kernel_size,
        icmp_ln48_1 => icmp_ln48_reg_599,
        weights_address0 => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_weights_address0,
        weights_ce0 => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_weights_ce0,
        weights_q0 => weights_q0,
        sext_ln43 => sub_ln40_reg_652,
        input_r_address0 => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_input_r_address0,
        input_r_ce0 => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_input_r_ce0,
        input_r_q0 => input_r_q0,
        sext_ln36 => in_width,
        sum_V_1_out => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out,
        sum_V_1_out_ap_vld => grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out_ap_vld);

    sdiv_32ns_32s_32_36_seq_1_U35 : component accel_top_sdiv_32ns_32s_32_36_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_233_ap_start,
        done => grp_fu_233_ap_done,
        din0 => grp_fu_233_p0,
        din1 => stride,
        ce => ap_const_logic_1,
        dout => grp_fu_233_p2);

    sdiv_32ns_32s_32_36_seq_1_U36 : component accel_top_sdiv_32ns_32s_32_36_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_251_ap_start,
        done => grp_fu_251_ap_done,
        din0 => grp_fu_251_p0,
        din1 => stride,
        ce => ap_const_logic_1,
        dout => grp_fu_251_p2);

    mul_32ns_32ns_64_1_1_U37 : component accel_top_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => bound_fu_275_p0,
        din1 => bound_fu_275_p1,
        dout => bound_fu_275_p2);

    mul_32ns_64ns_96_5_1_U38 : component accel_top_mul_32ns_64ns_96_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 64,
        dout_WIDTH => 96)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_288_p0,
        din1 => grp_fu_288_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_288_p2);

    mul_32ns_32ns_64_1_1_U39 : component accel_top_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => bound32_fu_312_p0,
        din1 => bound32_fu_312_p1,
        dout => bound32_fu_312_p2);

    mul_32s_32s_32_1_1_U40 : component accel_top_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => select_ln36_1_reg_618,
        din1 => stride,
        dout => mul_ln36_fu_412_p2);

    mul_32s_32s_32_1_1_U41 : component accel_top_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => select_ln36_reg_612,
        din1 => stride,
        dout => mul_ln40_fu_416_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state40)) then 
                    grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_ready = ap_const_logic_1)) then 
                    grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten34_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten34_fu_78 <= ap_const_lv64_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state42)) then 
                indvar_flatten34_fu_78 <= add_ln36_1_reg_607;
            end if; 
        end if;
    end process;

    oh_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                oh_fu_74 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state42)) then 
                oh_fu_74 <= select_ln36_1_reg_618;
            end if; 
        end if;
    end process;

    ow_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ow_fu_70 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state42)) then 
                ow_fu_70 <= add_ln39_fu_470_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state38)) then
                add_ln36_1_reg_607 <= add_ln36_1_fu_331_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state38) and (icmp_ln36_fu_326_p2 = ap_const_lv1_0))) then
                add_ln63_reg_628 <= add_ln63_fu_402_p2;
                select_ln36_1_reg_618 <= select_ln36_1_fu_362_p3;
                select_ln36_reg_612 <= select_ln36_fu_354_p3;
                trunc_ln36_reg_624 <= trunc_ln36_fu_388_p1;
                trunc_ln63_reg_633 <= trunc_ln63_fu_408_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state40)) then
                and_ln52_3_reg_657 <= and_ln52_3_fu_449_p2;
                sub_ln36_reg_647 <= sub_ln36_fu_420_p2;
                sub_ln40_reg_652 <= sub_ln40_fu_425_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state37)) then
                bound32_reg_594 <= bound32_fu_312_p2;
                bound4_reg_589 <= grp_fu_288_p2;
                icmp_ln48_reg_599 <= icmp_ln48_fu_318_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state32)) then
                bound_reg_557 <= bound_fu_275_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state39)) then
                mul_ln36_reg_637 <= mul_ln36_fu_412_p2;
                mul_ln40_reg_642 <= mul_ln40_fu_416_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state36)) then
                out_height_reg_573 <= out_height_fu_294_p2;
                out_width_reg_578 <= out_width_fu_300_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state38, icmp_ln36_fu_326_p2, grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_done, ap_CS_fsm_state41)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state38) and (icmp_ln36_fu_326_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state39;
                end if;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                if (((grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state41))) then
                    ap_NS_fsm <= ap_ST_fsm_state42;
                else
                    ap_NS_fsm <= ap_ST_fsm_state41;
                end if;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln36_1_fu_331_p2 <= std_logic_vector(unsigned(indvar_flatten34_fu_78) + unsigned(ap_const_lv64_1));
    add_ln36_fu_343_p2 <= std_logic_vector(unsigned(oh_fu_74) + unsigned(ap_const_lv32_1));
    add_ln39_fu_470_p2 <= std_logic_vector(signed(select_ln36_reg_612) + signed(ap_const_lv32_1));
    add_ln63_fu_402_p2 <= std_logic_vector(unsigned(tmp_4_fu_380_p3) + unsigned(lshr_ln63_1_fu_392_p4));
    and_ln52_3_fu_449_p2 <= (xor_ln46_fu_438_p2 and icmp_ln46_fu_444_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state32 <= ap_CS_fsm(31);
    ap_CS_fsm_state33 <= ap_CS_fsm(32);
    ap_CS_fsm_state36 <= ap_CS_fsm(35);
    ap_CS_fsm_state37 <= ap_CS_fsm(36);
    ap_CS_fsm_state38 <= ap_CS_fsm(37);
    ap_CS_fsm_state39 <= ap_CS_fsm(38);
    ap_CS_fsm_state40 <= ap_CS_fsm(39);
    ap_CS_fsm_state41 <= ap_CS_fsm(40);
    ap_CS_fsm_state42 <= ap_CS_fsm(41);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state39_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state40_blk <= ap_const_logic_0;

    ap_ST_fsm_state41_blk_assign_proc : process(grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_done)
    begin
        if ((grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state41_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state41_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state42_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state38, icmp_ln36_fu_326_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state38) and (icmp_ln36_fu_326_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state38, icmp_ln36_fu_326_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) and (icmp_ln36_fu_326_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound32_fu_312_p0 <= bound32_fu_312_p00(32 - 1 downto 0);
    bound32_fu_312_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_height_reg_573),64));
    bound32_fu_312_p1 <= bound32_fu_312_p10(32 - 1 downto 0);
    bound32_fu_312_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_width_reg_578),64));
    bound_fu_275_p0 <= cast_fu_272_p1(32 - 1 downto 0);
    bound_fu_275_p1 <= cast_fu_272_p1(32 - 1 downto 0);
    cast_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kernel_size),64));
    grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_ap_start_reg;

    grp_fu_233_ap_start_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_fu_233_ap_start <= ap_const_logic_1;
        else 
            grp_fu_233_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_233_p0 <= std_logic_vector(unsigned(sub_ln33_fu_221_p2) + unsigned(shl_ln33_fu_215_p2));

    grp_fu_251_ap_start_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_fu_251_ap_start <= ap_const_logic_1;
        else 
            grp_fu_251_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_251_p0 <= std_logic_vector(unsigned(sub_ln34_fu_239_p2) + unsigned(shl_ln33_fu_215_p2));
    grp_fu_288_p0 <= grp_fu_288_p00(32 - 1 downto 0);
    grp_fu_288_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels),96));
    grp_fu_288_p1 <= grp_fu_288_p10(64 - 1 downto 0);
    grp_fu_288_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bound_reg_557),96));
    icmp_ln36_fu_326_p2 <= "1" when (indvar_flatten34_fu_78 = bound32_reg_594) else "0";
    icmp_ln39_fu_349_p2 <= "1" when (ow_fu_70 = out_width_reg_578) else "0";
    icmp_ln46_fu_444_p2 <= "1" when (signed(sub_ln36_fu_420_p2) < signed(in_height)) else "0";
    icmp_ln48_fu_318_p2 <= "1" when (kernel_size = ap_const_lv32_0) else "0";
    input_r_address0 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_input_r_address0;
    input_r_ce0 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_input_r_ce0;
    lshr_ln63_1_fu_392_p4 <= select_ln36_fu_354_p3(8 downto 1);
    out_height_fu_294_p2 <= std_logic_vector(unsigned(grp_fu_233_p2) + unsigned(ap_const_lv32_1));
    out_width_fu_300_p2 <= std_logic_vector(unsigned(grp_fu_251_p2) + unsigned(ap_const_lv32_1));
    output_0_0_address1 <= zext_ln63_fu_463_p1(8 - 1 downto 0);

    output_0_0_ce1_assign_proc : process(ap_CS_fsm_state42)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state42)) then 
            output_0_0_ce1 <= ap_const_logic_1;
        else 
            output_0_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_0_0_d1 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out;

    output_0_0_we1_assign_proc : process(trunc_ln36_reg_624, trunc_ln63_reg_633, ap_CS_fsm_state42)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state42) and (trunc_ln63_reg_633 = ap_const_lv1_0) and (trunc_ln36_reg_624 = ap_const_lv1_0))) then 
            output_0_0_we1 <= ap_const_logic_1;
        else 
            output_0_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    output_0_1_address1 <= zext_ln63_fu_463_p1(8 - 1 downto 0);

    output_0_1_ce1_assign_proc : process(ap_CS_fsm_state42)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state42)) then 
            output_0_1_ce1 <= ap_const_logic_1;
        else 
            output_0_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_0_1_d1 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out;

    output_0_1_we1_assign_proc : process(trunc_ln36_reg_624, trunc_ln63_reg_633, ap_CS_fsm_state42)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state42) and (trunc_ln63_reg_633 = ap_const_lv1_1) and (trunc_ln36_reg_624 = ap_const_lv1_0))) then 
            output_0_1_we1 <= ap_const_logic_1;
        else 
            output_0_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_0_address1 <= zext_ln63_fu_463_p1(8 - 1 downto 0);

    output_1_0_ce1_assign_proc : process(ap_CS_fsm_state42)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state42)) then 
            output_1_0_ce1 <= ap_const_logic_1;
        else 
            output_1_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_0_d1 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out;

    output_1_0_we1_assign_proc : process(trunc_ln36_reg_624, trunc_ln63_reg_633, ap_CS_fsm_state42)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state42) and (trunc_ln63_reg_633 = ap_const_lv1_0) and (trunc_ln36_reg_624 = ap_const_lv1_1))) then 
            output_1_0_we1 <= ap_const_logic_1;
        else 
            output_1_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_1_address1 <= zext_ln63_fu_463_p1(8 - 1 downto 0);

    output_1_1_ce1_assign_proc : process(ap_CS_fsm_state42)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state42)) then 
            output_1_1_ce1 <= ap_const_logic_1;
        else 
            output_1_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_1_d1 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_sum_V_1_out;

    output_1_1_we1_assign_proc : process(trunc_ln36_reg_624, trunc_ln63_reg_633, ap_CS_fsm_state42)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state42) and (trunc_ln63_reg_633 = ap_const_lv1_1) and (trunc_ln36_reg_624 = ap_const_lv1_1))) then 
            output_1_1_we1 <= ap_const_logic_1;
        else 
            output_1_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln36_1_fu_362_p3 <= 
        add_ln36_fu_343_p2 when (icmp_ln39_fu_349_p2(0) = '1') else 
        oh_fu_74;
    select_ln36_fu_354_p3 <= 
        ap_const_lv32_0 when (icmp_ln39_fu_349_p2(0) = '1') else 
        ow_fu_70;
    shl_ln33_fu_215_p2 <= std_logic_vector(shift_left(unsigned(padding),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    sub_ln33_fu_221_p2 <= std_logic_vector(unsigned(in_height) - unsigned(kernel_size));
    sub_ln34_fu_239_p2 <= std_logic_vector(unsigned(in_width) - unsigned(kernel_size));
    sub_ln36_fu_420_p2 <= std_logic_vector(unsigned(mul_ln36_reg_637) - unsigned(padding));
    sub_ln40_fu_425_p2 <= std_logic_vector(unsigned(mul_ln40_reg_642) - unsigned(padding));
    tmp_4_fu_380_p3 <= (zext_ln63_mid2_v_fu_370_p4 & ap_const_lv4_0);
    tmp_fu_430_p3 <= sub_ln36_fu_420_p2(31 downto 31);
    trunc_ln36_fu_388_p1 <= select_ln36_1_fu_362_p3(1 - 1 downto 0);
    trunc_ln63_fu_408_p1 <= select_ln36_fu_354_p3(1 - 1 downto 0);
    weights_address0 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_weights_address0;
    weights_ce0 <= grp_conv_engine_Pipeline_CONV_IC_CONV_KH_CONV_KW_fu_196_weights_ce0;
    xor_ln46_fu_438_p2 <= (tmp_fu_430_p3 xor ap_const_lv1_1);
    zext_ln63_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_reg_628),64));
    zext_ln63_mid2_v_fu_370_p4 <= select_ln36_1_fu_362_p3(4 downto 1);
end behav;
