// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accel_top_accel_top_Pipeline_LOAD_INPUT_H_LOAD_INPUT_W (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_DATA_AWVALID,
        m_axi_DATA_AWREADY,
        m_axi_DATA_AWADDR,
        m_axi_DATA_AWID,
        m_axi_DATA_AWLEN,
        m_axi_DATA_AWSIZE,
        m_axi_DATA_AWBURST,
        m_axi_DATA_AWLOCK,
        m_axi_DATA_AWCACHE,
        m_axi_DATA_AWPROT,
        m_axi_DATA_AWQOS,
        m_axi_DATA_AWREGION,
        m_axi_DATA_AWUSER,
        m_axi_DATA_WVALID,
        m_axi_DATA_WREADY,
        m_axi_DATA_WDATA,
        m_axi_DATA_WSTRB,
        m_axi_DATA_WLAST,
        m_axi_DATA_WID,
        m_axi_DATA_WUSER,
        m_axi_DATA_ARVALID,
        m_axi_DATA_ARREADY,
        m_axi_DATA_ARADDR,
        m_axi_DATA_ARID,
        m_axi_DATA_ARLEN,
        m_axi_DATA_ARSIZE,
        m_axi_DATA_ARBURST,
        m_axi_DATA_ARLOCK,
        m_axi_DATA_ARCACHE,
        m_axi_DATA_ARPROT,
        m_axi_DATA_ARQOS,
        m_axi_DATA_ARREGION,
        m_axi_DATA_ARUSER,
        m_axi_DATA_RVALID,
        m_axi_DATA_RREADY,
        m_axi_DATA_RDATA,
        m_axi_DATA_RLAST,
        m_axi_DATA_RID,
        m_axi_DATA_RFIFONUM,
        m_axi_DATA_RUSER,
        m_axi_DATA_RRESP,
        m_axi_DATA_BVALID,
        m_axi_DATA_BREADY,
        m_axi_DATA_BRESP,
        m_axi_DATA_BID,
        m_axi_DATA_BUSER,
        in_width,
        mul_ln24,
        zext_ln91,
        zext_ln87,
        in_ptr,
        input_data,
        local_input_V_address1,
        local_input_V_ce1,
        local_input_V_we1,
        local_input_V_d1,
        trunc_ln89_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_DATA_AWVALID;
input   m_axi_DATA_AWREADY;
output  [63:0] m_axi_DATA_AWADDR;
output  [0:0] m_axi_DATA_AWID;
output  [31:0] m_axi_DATA_AWLEN;
output  [2:0] m_axi_DATA_AWSIZE;
output  [1:0] m_axi_DATA_AWBURST;
output  [1:0] m_axi_DATA_AWLOCK;
output  [3:0] m_axi_DATA_AWCACHE;
output  [2:0] m_axi_DATA_AWPROT;
output  [3:0] m_axi_DATA_AWQOS;
output  [3:0] m_axi_DATA_AWREGION;
output  [0:0] m_axi_DATA_AWUSER;
output   m_axi_DATA_WVALID;
input   m_axi_DATA_WREADY;
output  [31:0] m_axi_DATA_WDATA;
output  [3:0] m_axi_DATA_WSTRB;
output   m_axi_DATA_WLAST;
output  [0:0] m_axi_DATA_WID;
output  [0:0] m_axi_DATA_WUSER;
output   m_axi_DATA_ARVALID;
input   m_axi_DATA_ARREADY;
output  [63:0] m_axi_DATA_ARADDR;
output  [0:0] m_axi_DATA_ARID;
output  [31:0] m_axi_DATA_ARLEN;
output  [2:0] m_axi_DATA_ARSIZE;
output  [1:0] m_axi_DATA_ARBURST;
output  [1:0] m_axi_DATA_ARLOCK;
output  [3:0] m_axi_DATA_ARCACHE;
output  [2:0] m_axi_DATA_ARPROT;
output  [3:0] m_axi_DATA_ARQOS;
output  [3:0] m_axi_DATA_ARREGION;
output  [0:0] m_axi_DATA_ARUSER;
input   m_axi_DATA_RVALID;
output   m_axi_DATA_RREADY;
input  [31:0] m_axi_DATA_RDATA;
input   m_axi_DATA_RLAST;
input  [0:0] m_axi_DATA_RID;
input  [8:0] m_axi_DATA_RFIFONUM;
input  [0:0] m_axi_DATA_RUSER;
input  [1:0] m_axi_DATA_RRESP;
input   m_axi_DATA_BVALID;
output   m_axi_DATA_BREADY;
input  [1:0] m_axi_DATA_BRESP;
input  [0:0] m_axi_DATA_BID;
input  [0:0] m_axi_DATA_BUSER;
input  [31:0] in_width;
input  [62:0] mul_ln24;
input  [36:0] zext_ln91;
input  [30:0] zext_ln87;
input  [31:0] in_ptr;
input  [63:0] input_data;
output  [15:0] local_input_V_address1;
output   local_input_V_ce1;
output   local_input_V_we1;
output  [7:0] local_input_V_d1;
input  [1:0] trunc_ln89_1;

reg ap_idle;
reg m_axi_DATA_ARVALID;
reg m_axi_DATA_RREADY;
reg local_input_V_ce1;
reg local_input_V_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln88_fu_221_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    DATA_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    DATA_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln87_cast_fu_183_p1;
reg   [31:0] zext_ln87_cast_reg_444;
wire   [10:0] trunc_ln91_fu_187_p1;
reg   [10:0] trunc_ln91_reg_449;
wire   [16:0] select_ln88_fu_241_p3;
reg   [16:0] select_ln88_reg_458;
reg   [16:0] select_ln88_reg_458_pp0_iter2_reg;
wire   [30:0] select_ln88_1_fu_249_p3;
reg   [30:0] select_ln88_1_reg_463;
wire   [15:0] add_ln91_4_fu_278_p2;
reg   [15:0] add_ln91_4_reg_468;
reg   [15:0] add_ln91_4_reg_468_pp0_iter2_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter3_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter4_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter5_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter6_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter7_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter8_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter9_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter10_reg;
reg   [15:0] add_ln91_4_reg_468_pp0_iter11_reg;
wire   [1:0] trunc_ln91_4_fu_284_p1;
reg   [1:0] trunc_ln91_4_reg_473;
reg   [1:0] trunc_ln91_4_reg_473_pp0_iter2_reg;
wire   [31:0] mul_ln88_fu_312_p2;
reg   [31:0] mul_ln88_reg_478;
reg   [63:0] DATA_addr_reg_483;
wire   [1:0] add_ln91_2_fu_367_p2;
reg   [1:0] add_ln91_2_reg_489;
reg   [1:0] add_ln91_2_reg_489_pp0_iter4_reg;
reg   [1:0] add_ln91_2_reg_489_pp0_iter5_reg;
reg   [1:0] add_ln91_2_reg_489_pp0_iter6_reg;
reg   [1:0] add_ln91_2_reg_489_pp0_iter7_reg;
reg   [1:0] add_ln91_2_reg_489_pp0_iter8_reg;
reg   [1:0] add_ln91_2_reg_489_pp0_iter9_reg;
reg   [1:0] add_ln91_2_reg_489_pp0_iter10_reg;
reg   [1:0] add_ln91_2_reg_489_pp0_iter11_reg;
reg   [31:0] DATA_addr_read_reg_494;
wire   [63:0] zext_ln91_2_fu_373_p1;
wire  signed [63:0] sext_ln91_fu_353_p1;
reg   [16:0] w_fu_100;
wire   [16:0] add_ln89_fu_288_p2;
wire    ap_loop_init;
reg   [30:0] h_fu_104;
reg   [62:0] indvar_flatten_fu_108;
wire   [62:0] add_ln88_fu_226_p2;
wire   [31:0] zext_ln89_fu_212_p1;
wire   [0:0] icmp_ln89_fu_216_p2;
wire   [30:0] add_ln88_1_fu_235_p2;
wire   [10:0] trunc_ln91_1_fu_257_p1;
wire   [10:0] add_ln91_1_fu_261_p2;
wire   [15:0] tmp_s_fu_266_p3;
wire   [15:0] trunc_ln91_3_fu_274_p1;
wire   [30:0] mul_ln88_fu_312_p0;
wire   [30:0] mul_ln88_fu_312_p1;
wire  signed [31:0] add_ln88_2_fu_317_p2;
wire  signed [63:0] sext_ln88_fu_325_p1;
wire   [63:0] add_ln88_3_fu_329_p2;
wire   [63:0] zext_ln89_1_fu_334_p1;
wire   [63:0] add_ln91_fu_337_p2;
wire   [61:0] trunc_ln91_2_fu_343_p4;
wire   [1:0] add_ln91_3_fu_363_p2;
wire   [1:0] trunc_ln88_fu_321_p1;
wire   [4:0] shl_ln1_fu_377_p3;
wire   [31:0] zext_ln91_1_fu_384_p1;
wire   [31:0] lshr_ln91_fu_388_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [31:0] mul_ln88_fu_312_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

accel_top_mul_31ns_31ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_31ns_31ns_32_1_1_U1(
    .din0(mul_ln88_fu_312_p0),
    .din1(mul_ln88_fu_312_p1),
    .dout(mul_ln88_fu_312_p2)
);

accel_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_fu_104 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln88_fu_221_p2 == 1'd0))) begin
            h_fu_104 <= select_ln88_1_fu_249_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_108 <= 63'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln88_fu_221_p2 == 1'd0))) begin
            indvar_flatten_fu_108 <= add_ln88_fu_226_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_100 <= 17'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln88_fu_221_p2 == 1'd0))) begin
            w_fu_100 <= add_ln89_fu_288_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        DATA_addr_read_reg_494 <= m_axi_DATA_RDATA;
        DATA_addr_reg_483 <= sext_ln91_fu_353_p1;
        add_ln91_2_reg_489 <= add_ln91_2_fu_367_p2;
        add_ln91_2_reg_489_pp0_iter10_reg <= add_ln91_2_reg_489_pp0_iter9_reg;
        add_ln91_2_reg_489_pp0_iter11_reg <= add_ln91_2_reg_489_pp0_iter10_reg;
        add_ln91_2_reg_489_pp0_iter4_reg <= add_ln91_2_reg_489;
        add_ln91_2_reg_489_pp0_iter5_reg <= add_ln91_2_reg_489_pp0_iter4_reg;
        add_ln91_2_reg_489_pp0_iter6_reg <= add_ln91_2_reg_489_pp0_iter5_reg;
        add_ln91_2_reg_489_pp0_iter7_reg <= add_ln91_2_reg_489_pp0_iter6_reg;
        add_ln91_2_reg_489_pp0_iter8_reg <= add_ln91_2_reg_489_pp0_iter7_reg;
        add_ln91_2_reg_489_pp0_iter9_reg <= add_ln91_2_reg_489_pp0_iter8_reg;
        add_ln91_4_reg_468_pp0_iter10_reg <= add_ln91_4_reg_468_pp0_iter9_reg;
        add_ln91_4_reg_468_pp0_iter11_reg <= add_ln91_4_reg_468_pp0_iter10_reg;
        add_ln91_4_reg_468_pp0_iter2_reg <= add_ln91_4_reg_468;
        add_ln91_4_reg_468_pp0_iter3_reg <= add_ln91_4_reg_468_pp0_iter2_reg;
        add_ln91_4_reg_468_pp0_iter4_reg <= add_ln91_4_reg_468_pp0_iter3_reg;
        add_ln91_4_reg_468_pp0_iter5_reg <= add_ln91_4_reg_468_pp0_iter4_reg;
        add_ln91_4_reg_468_pp0_iter6_reg <= add_ln91_4_reg_468_pp0_iter5_reg;
        add_ln91_4_reg_468_pp0_iter7_reg <= add_ln91_4_reg_468_pp0_iter6_reg;
        add_ln91_4_reg_468_pp0_iter8_reg <= add_ln91_4_reg_468_pp0_iter7_reg;
        add_ln91_4_reg_468_pp0_iter9_reg <= add_ln91_4_reg_468_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        mul_ln88_reg_478 <= mul_ln88_fu_312_p2;
        select_ln88_reg_458_pp0_iter2_reg <= select_ln88_reg_458;
        trunc_ln91_4_reg_473_pp0_iter2_reg <= trunc_ln91_4_reg_473;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln88_fu_221_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln91_4_reg_468 <= add_ln91_4_fu_278_p2;
        select_ln88_1_reg_463 <= select_ln88_1_fu_249_p3;
        select_ln88_reg_458 <= select_ln88_fu_241_p3;
        trunc_ln91_4_reg_473 <= trunc_ln91_4_fu_284_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        trunc_ln91_reg_449 <= trunc_ln91_fu_187_p1;
        zext_ln87_cast_reg_444[30 : 0] <= zext_ln87_cast_fu_183_p1[30 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        DATA_blk_n_AR = m_axi_DATA_ARREADY;
    end else begin
        DATA_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        DATA_blk_n_R = m_axi_DATA_RVALID;
    end else begin
        DATA_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln88_fu_221_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_input_V_ce1 = 1'b1;
    end else begin
        local_input_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_input_V_we1 = 1'b1;
    end else begin
        local_input_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_DATA_ARVALID = 1'b1;
    end else begin
        m_axi_DATA_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_DATA_RREADY = 1'b1;
    end else begin
        m_axi_DATA_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln88_1_fu_235_p2 = (h_fu_104 + 31'd1);

assign add_ln88_2_fu_317_p2 = (mul_ln88_reg_478 + in_ptr);

assign add_ln88_3_fu_329_p2 = ($signed(sext_ln88_fu_325_p1) + $signed(input_data));

assign add_ln88_fu_226_p2 = (indvar_flatten_fu_108 + 63'd1);

assign add_ln89_fu_288_p2 = (select_ln88_fu_241_p3 + 17'd1);

assign add_ln91_1_fu_261_p2 = (trunc_ln91_reg_449 + trunc_ln91_1_fu_257_p1);

assign add_ln91_2_fu_367_p2 = (add_ln91_3_fu_363_p2 + trunc_ln88_fu_321_p1);

assign add_ln91_3_fu_363_p2 = (trunc_ln89_1 + trunc_ln91_4_reg_473_pp0_iter2_reg);

assign add_ln91_4_fu_278_p2 = (tmp_s_fu_266_p3 + trunc_ln91_3_fu_274_p1);

assign add_ln91_fu_337_p2 = (add_ln88_3_fu_329_p2 + zext_ln89_1_fu_334_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_DATA_RVALID == 1'b0)) | ((m_axi_DATA_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_DATA_RVALID == 1'b0)) | ((m_axi_DATA_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = (m_axi_DATA_RVALID == 1'b0);
end

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln88_fu_221_p2 = ((indvar_flatten_fu_108 == mul_ln24) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_216_p2 = ((zext_ln89_fu_212_p1 == in_width) ? 1'b1 : 1'b0);

assign local_input_V_address1 = zext_ln91_2_fu_373_p1;

assign local_input_V_d1 = lshr_ln91_fu_388_p2[7:0];

assign lshr_ln91_fu_388_p2 = DATA_addr_read_reg_494 >> zext_ln91_1_fu_384_p1;

assign m_axi_DATA_ARADDR = DATA_addr_reg_483;

assign m_axi_DATA_ARBURST = 2'd0;

assign m_axi_DATA_ARCACHE = 4'd0;

assign m_axi_DATA_ARID = 1'd0;

assign m_axi_DATA_ARLEN = 32'd1;

assign m_axi_DATA_ARLOCK = 2'd0;

assign m_axi_DATA_ARPROT = 3'd0;

assign m_axi_DATA_ARQOS = 4'd0;

assign m_axi_DATA_ARREGION = 4'd0;

assign m_axi_DATA_ARSIZE = 3'd0;

assign m_axi_DATA_ARUSER = 1'd0;

assign m_axi_DATA_AWADDR = 64'd0;

assign m_axi_DATA_AWBURST = 2'd0;

assign m_axi_DATA_AWCACHE = 4'd0;

assign m_axi_DATA_AWID = 1'd0;

assign m_axi_DATA_AWLEN = 32'd0;

assign m_axi_DATA_AWLOCK = 2'd0;

assign m_axi_DATA_AWPROT = 3'd0;

assign m_axi_DATA_AWQOS = 4'd0;

assign m_axi_DATA_AWREGION = 4'd0;

assign m_axi_DATA_AWSIZE = 3'd0;

assign m_axi_DATA_AWUSER = 1'd0;

assign m_axi_DATA_AWVALID = 1'b0;

assign m_axi_DATA_BREADY = 1'b0;

assign m_axi_DATA_WDATA = 32'd0;

assign m_axi_DATA_WID = 1'd0;

assign m_axi_DATA_WLAST = 1'b0;

assign m_axi_DATA_WSTRB = 4'd0;

assign m_axi_DATA_WUSER = 1'd0;

assign m_axi_DATA_WVALID = 1'b0;

assign mul_ln88_fu_312_p0 = mul_ln88_fu_312_p00;

assign mul_ln88_fu_312_p00 = select_ln88_1_reg_463;

assign mul_ln88_fu_312_p1 = zext_ln87_cast_reg_444;

assign select_ln88_1_fu_249_p3 = ((icmp_ln89_fu_216_p2[0:0] == 1'b1) ? add_ln88_1_fu_235_p2 : h_fu_104);

assign select_ln88_fu_241_p3 = ((icmp_ln89_fu_216_p2[0:0] == 1'b1) ? 17'd0 : w_fu_100);

assign sext_ln88_fu_325_p1 = add_ln88_2_fu_317_p2;

assign sext_ln91_fu_353_p1 = $signed(trunc_ln91_2_fu_343_p4);

assign shl_ln1_fu_377_p3 = {{add_ln91_2_reg_489_pp0_iter11_reg}, {3'd0}};

assign tmp_s_fu_266_p3 = {{add_ln91_1_fu_261_p2}, {5'd0}};

assign trunc_ln88_fu_321_p1 = add_ln88_2_fu_317_p2[1:0];

assign trunc_ln91_1_fu_257_p1 = select_ln88_1_fu_249_p3[10:0];

assign trunc_ln91_2_fu_343_p4 = {{add_ln91_fu_337_p2[63:2]}};

assign trunc_ln91_3_fu_274_p1 = select_ln88_fu_241_p3[15:0];

assign trunc_ln91_4_fu_284_p1 = select_ln88_fu_241_p3[1:0];

assign trunc_ln91_fu_187_p1 = zext_ln91[10:0];

assign zext_ln87_cast_fu_183_p1 = zext_ln87;

assign zext_ln89_1_fu_334_p1 = select_ln88_reg_458_pp0_iter2_reg;

assign zext_ln89_fu_212_p1 = w_fu_100;

assign zext_ln91_1_fu_384_p1 = shl_ln1_fu_377_p3;

assign zext_ln91_2_fu_373_p1 = add_ln91_4_reg_468_pp0_iter11_reg;

always @ (posedge ap_clk) begin
    zext_ln87_cast_reg_444[31] <= 1'b0;
end

endmodule //accel_top_accel_top_Pipeline_LOAD_INPUT_H_LOAD_INPUT_W
