// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module accel_top_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_width,
        bound,
        input_0_0_address0,
        input_0_0_ce0,
        input_0_0_q0,
        input_0_1_address0,
        input_0_1_ce0,
        input_0_1_q0,
        input_1_0_address0,
        input_1_0_ce0,
        input_1_0_q0,
        input_1_1_address0,
        input_1_1_ce0,
        input_1_1_q0,
        output_r_address1,
        output_r_ce1,
        output_r_we1,
        output_r_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] out_width;
input  [63:0] bound;
output  [7:0] input_0_0_address0;
output   input_0_0_ce0;
input  [31:0] input_0_0_q0;
output  [7:0] input_0_1_address0;
output   input_0_1_ce0;
input  [31:0] input_0_1_q0;
output  [7:0] input_1_0_address0;
output   input_1_0_ce0;
input  [31:0] input_1_0_q0;
output  [7:0] input_1_1_address0;
output   input_1_1_ce0;
input  [31:0] input_1_1_q0;
output  [9:0] output_r_address1;
output   output_r_ce1;
output   output_r_we1;
output  [31:0] output_r_d1;

reg ap_idle;
reg input_0_0_ce0;
reg input_0_1_ce0;
reg input_1_0_ce0;
reg input_1_1_ce0;
reg output_r_ce1;
reg output_r_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln25_fu_179_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] add_ln38_fu_261_p2;
reg   [9:0] add_ln38_reg_386;
reg   [9:0] add_ln38_reg_386_pp0_iter2_reg;
wire   [31:0] select_ln34_fu_294_p3;
reg   [31:0] select_ln34_reg_391;
wire   [31:0] select_ln35_fu_308_p3;
reg   [31:0] select_ln35_reg_397;
wire   [63:0] zext_ln29_fu_253_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln38_fu_316_p1;
reg   [10:0] ow_fu_56;
wire   [10:0] add_ln26_fu_267_p2;
wire    ap_loop_init;
reg   [31:0] oh_fu_60;
wire   [31:0] select_ln25_1_fu_207_p3;
reg   [63:0] indvar_flatten_fu_64;
wire   [63:0] add_ln25_1_fu_184_p2;
wire   [31:0] zext_ln26_fu_170_p1;
wire   [0:0] icmp_ln26_fu_174_p2;
wire   [31:0] add_ln25_fu_193_p2;
wire   [3:0] trunc_ln29_1_fu_219_p1;
wire   [4:0] trunc_ln29_fu_215_p1;
wire   [10:0] select_ln25_fu_199_p3;
wire   [7:0] tmp_fu_223_p3;
wire   [7:0] trunc_ln29_3_fu_243_p1;
wire   [7:0] add_ln29_fu_247_p2;
wire   [9:0] tmp_3_fu_231_p3;
wire   [9:0] trunc_ln29_2_fu_239_p1;
wire   [0:0] icmp_ln1081_fu_288_p2;
wire   [0:0] icmp_ln1081_1_fu_302_p2;
wire   [0:0] icmp_ln1081_2_fu_320_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

accel_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_64 <= 64'd0;
        end else if (((icmp_ln25_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_64 <= add_ln25_1_fu_184_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            oh_fu_60 <= 32'd0;
        end else if (((icmp_ln25_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            oh_fu_60 <= select_ln25_1_fu_207_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ow_fu_56 <= 11'd0;
        end else if (((icmp_ln25_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ow_fu_56 <= add_ln26_fu_267_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln25_fu_179_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln38_reg_386 <= add_ln38_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln38_reg_386_pp0_iter2_reg <= add_ln38_reg_386;
        select_ln34_reg_391 <= select_ln34_fu_294_p3;
        select_ln35_reg_397 <= select_ln35_fu_308_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_179_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_0_0_ce0 = 1'b1;
    end else begin
        input_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_0_1_ce0 = 1'b1;
    end else begin
        input_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_0_ce0 = 1'b1;
    end else begin
        input_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_1_ce0 = 1'b1;
    end else begin
        input_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        output_r_ce1 = 1'b1;
    end else begin
        output_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        output_r_we1 = 1'b1;
    end else begin
        output_r_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_1_fu_184_p2 = (indvar_flatten_fu_64 + 64'd1);

assign add_ln25_fu_193_p2 = (oh_fu_60 + 32'd1);

assign add_ln26_fu_267_p2 = (select_ln25_fu_199_p3 + 11'd1);

assign add_ln29_fu_247_p2 = (tmp_fu_223_p3 + trunc_ln29_3_fu_243_p1);

assign add_ln38_fu_261_p2 = (tmp_3_fu_231_p3 + trunc_ln29_2_fu_239_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln1081_1_fu_302_p2 = (($signed(input_1_0_q0) > $signed(input_1_1_q0)) ? 1'b1 : 1'b0);

assign icmp_ln1081_2_fu_320_p2 = (($signed(select_ln34_reg_391) > $signed(select_ln35_reg_397)) ? 1'b1 : 1'b0);

assign icmp_ln1081_fu_288_p2 = (($signed(input_0_0_q0) > $signed(input_0_1_q0)) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_179_p2 = ((indvar_flatten_fu_64 == bound) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_174_p2 = ((zext_ln26_fu_170_p1 == out_width) ? 1'b1 : 1'b0);

assign input_0_0_address0 = zext_ln29_fu_253_p1;

assign input_0_1_address0 = zext_ln29_fu_253_p1;

assign input_1_0_address0 = zext_ln29_fu_253_p1;

assign input_1_1_address0 = zext_ln29_fu_253_p1;

assign output_r_address1 = zext_ln38_fu_316_p1;

assign output_r_d1 = ((icmp_ln1081_2_fu_320_p2[0:0] == 1'b1) ? select_ln34_reg_391 : select_ln35_reg_397);

assign select_ln25_1_fu_207_p3 = ((icmp_ln26_fu_174_p2[0:0] == 1'b1) ? add_ln25_fu_193_p2 : oh_fu_60);

assign select_ln25_fu_199_p3 = ((icmp_ln26_fu_174_p2[0:0] == 1'b1) ? 11'd0 : ow_fu_56);

assign select_ln34_fu_294_p3 = ((icmp_ln1081_fu_288_p2[0:0] == 1'b1) ? input_0_0_q0 : input_0_1_q0);

assign select_ln35_fu_308_p3 = ((icmp_ln1081_1_fu_302_p2[0:0] == 1'b1) ? input_1_0_q0 : input_1_1_q0);

assign tmp_3_fu_231_p3 = {{trunc_ln29_fu_215_p1}, {5'd0}};

assign tmp_fu_223_p3 = {{trunc_ln29_1_fu_219_p1}, {4'd0}};

assign trunc_ln29_1_fu_219_p1 = select_ln25_1_fu_207_p3[3:0];

assign trunc_ln29_2_fu_239_p1 = select_ln25_fu_199_p3[9:0];

assign trunc_ln29_3_fu_243_p1 = select_ln25_fu_199_p3[7:0];

assign trunc_ln29_fu_215_p1 = select_ln25_1_fu_207_p3[4:0];

assign zext_ln26_fu_170_p1 = ow_fu_56;

assign zext_ln29_fu_253_p1 = add_ln29_fu_247_p2;

assign zext_ln38_fu_316_p1 = add_ln38_reg_386_pp0_iter2_reg;

endmodule //accel_top_maxpool_2x2_Pipeline_POOL_ROW_POOL_COL
