// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module aes128_top_aes128_top_Pipeline_STORE_DATA (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_DATA_AWVALID,
        m_axi_DATA_AWREADY,
        m_axi_DATA_AWADDR,
        m_axi_DATA_AWID,
        m_axi_DATA_AWLEN,
        m_axi_DATA_AWSIZE,
        m_axi_DATA_AWBURST,
        m_axi_DATA_AWLOCK,
        m_axi_DATA_AWCACHE,
        m_axi_DATA_AWPROT,
        m_axi_DATA_AWQOS,
        m_axi_DATA_AWREGION,
        m_axi_DATA_AWUSER,
        m_axi_DATA_WVALID,
        m_axi_DATA_WREADY,
        m_axi_DATA_WDATA,
        m_axi_DATA_WSTRB,
        m_axi_DATA_WLAST,
        m_axi_DATA_WID,
        m_axi_DATA_WUSER,
        m_axi_DATA_ARVALID,
        m_axi_DATA_ARREADY,
        m_axi_DATA_ARADDR,
        m_axi_DATA_ARID,
        m_axi_DATA_ARLEN,
        m_axi_DATA_ARSIZE,
        m_axi_DATA_ARBURST,
        m_axi_DATA_ARLOCK,
        m_axi_DATA_ARCACHE,
        m_axi_DATA_ARPROT,
        m_axi_DATA_ARQOS,
        m_axi_DATA_ARREGION,
        m_axi_DATA_ARUSER,
        m_axi_DATA_RVALID,
        m_axi_DATA_RREADY,
        m_axi_DATA_RDATA,
        m_axi_DATA_RLAST,
        m_axi_DATA_RID,
        m_axi_DATA_RFIFONUM,
        m_axi_DATA_RUSER,
        m_axi_DATA_RRESP,
        m_axi_DATA_BVALID,
        m_axi_DATA_BREADY,
        m_axi_DATA_BRESP,
        m_axi_DATA_BID,
        m_axi_DATA_BUSER,
        sext_ln77,
        ciphertext_address0,
        ciphertext_ce0,
        ciphertext_q0,
        ciphertext_address1,
        ciphertext_ce1,
        ciphertext_q1,
        ciphertext_1_address0,
        ciphertext_1_ce0,
        ciphertext_1_q0,
        ciphertext_1_address1,
        ciphertext_1_ce1,
        ciphertext_1_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_DATA_AWVALID;
input   m_axi_DATA_AWREADY;
output  [63:0] m_axi_DATA_AWADDR;
output  [0:0] m_axi_DATA_AWID;
output  [31:0] m_axi_DATA_AWLEN;
output  [2:0] m_axi_DATA_AWSIZE;
output  [1:0] m_axi_DATA_AWBURST;
output  [1:0] m_axi_DATA_AWLOCK;
output  [3:0] m_axi_DATA_AWCACHE;
output  [2:0] m_axi_DATA_AWPROT;
output  [3:0] m_axi_DATA_AWQOS;
output  [3:0] m_axi_DATA_AWREGION;
output  [0:0] m_axi_DATA_AWUSER;
output   m_axi_DATA_WVALID;
input   m_axi_DATA_WREADY;
output  [31:0] m_axi_DATA_WDATA;
output  [3:0] m_axi_DATA_WSTRB;
output   m_axi_DATA_WLAST;
output  [0:0] m_axi_DATA_WID;
output  [0:0] m_axi_DATA_WUSER;
output   m_axi_DATA_ARVALID;
input   m_axi_DATA_ARREADY;
output  [63:0] m_axi_DATA_ARADDR;
output  [0:0] m_axi_DATA_ARID;
output  [31:0] m_axi_DATA_ARLEN;
output  [2:0] m_axi_DATA_ARSIZE;
output  [1:0] m_axi_DATA_ARBURST;
output  [1:0] m_axi_DATA_ARLOCK;
output  [3:0] m_axi_DATA_ARCACHE;
output  [2:0] m_axi_DATA_ARPROT;
output  [3:0] m_axi_DATA_ARQOS;
output  [3:0] m_axi_DATA_ARREGION;
output  [0:0] m_axi_DATA_ARUSER;
input   m_axi_DATA_RVALID;
output   m_axi_DATA_RREADY;
input  [31:0] m_axi_DATA_RDATA;
input   m_axi_DATA_RLAST;
input  [0:0] m_axi_DATA_RID;
input  [8:0] m_axi_DATA_RFIFONUM;
input  [0:0] m_axi_DATA_RUSER;
input  [1:0] m_axi_DATA_RRESP;
input   m_axi_DATA_BVALID;
output   m_axi_DATA_BREADY;
input  [1:0] m_axi_DATA_BRESP;
input  [0:0] m_axi_DATA_BID;
input  [0:0] m_axi_DATA_BUSER;
input  [61:0] sext_ln77;
output  [2:0] ciphertext_address0;
output   ciphertext_ce0;
input  [7:0] ciphertext_q0;
output  [2:0] ciphertext_address1;
output   ciphertext_ce1;
input  [7:0] ciphertext_q1;
output  [2:0] ciphertext_1_address0;
output   ciphertext_1_ce0;
input  [7:0] ciphertext_1_q0;
output  [2:0] ciphertext_1_address1;
output   ciphertext_1_ce1;
input  [7:0] ciphertext_1_q1;

reg ap_idle;
reg m_axi_DATA_WVALID;
reg ciphertext_ce0;
reg ciphertext_ce1;
reg ciphertext_1_ce0;
reg ciphertext_1_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln77_fu_136_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    DATA_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln77_reg_203;
reg   [7:0] ciphertext_load_reg_232;
reg   [7:0] ciphertext_1_load_reg_237;
reg   [7:0] ciphertext_load_1_reg_242;
reg   [7:0] ciphertext_1_load_1_reg_247;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln79_fu_154_p1;
wire   [63:0] zext_ln81_fu_166_p1;
wire    ap_block_pp0_stage0_01001;
reg   [2:0] i_fu_56;
wire   [2:0] add_ln77_fu_142_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_2;
wire   [2:0] shl_ln79_fu_148_p2;
wire   [2:0] or_ln81_fu_160_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

aes128_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln77_fu_136_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_56 <= add_ln77_fu_142_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln77_reg_203 <= icmp_ln77_fu_136_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln77_reg_203 == 1'd0))) begin
        ciphertext_1_load_1_reg_247 <= ciphertext_1_q0;
        ciphertext_1_load_reg_237 <= ciphertext_1_q1;
        ciphertext_load_1_reg_242 <= ciphertext_q0;
        ciphertext_load_reg_232 <= ciphertext_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        DATA_blk_n_W = m_axi_DATA_WREADY;
    end else begin
        DATA_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_136_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln77_reg_203 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ciphertext_1_ce0 = 1'b1;
    end else begin
        ciphertext_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ciphertext_1_ce1 = 1'b1;
    end else begin
        ciphertext_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ciphertext_ce0 = 1'b1;
    end else begin
        ciphertext_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ciphertext_ce1 = 1'b1;
    end else begin
        ciphertext_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_DATA_WVALID = 1'b1;
    end else begin
        m_axi_DATA_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln77_fu_142_p2 = (ap_sig_allocacmp_i_2 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_DATA_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_DATA_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ciphertext_1_address0 = zext_ln81_fu_166_p1;

assign ciphertext_1_address1 = zext_ln79_fu_154_p1;

assign ciphertext_address0 = zext_ln81_fu_166_p1;

assign ciphertext_address1 = zext_ln79_fu_154_p1;

assign icmp_ln77_fu_136_p2 = ((ap_sig_allocacmp_i_2 == 3'd4) ? 1'b1 : 1'b0);

assign m_axi_DATA_ARADDR = 64'd0;

assign m_axi_DATA_ARBURST = 2'd0;

assign m_axi_DATA_ARCACHE = 4'd0;

assign m_axi_DATA_ARID = 1'd0;

assign m_axi_DATA_ARLEN = 32'd0;

assign m_axi_DATA_ARLOCK = 2'd0;

assign m_axi_DATA_ARPROT = 3'd0;

assign m_axi_DATA_ARQOS = 4'd0;

assign m_axi_DATA_ARREGION = 4'd0;

assign m_axi_DATA_ARSIZE = 3'd0;

assign m_axi_DATA_ARUSER = 1'd0;

assign m_axi_DATA_ARVALID = 1'b0;

assign m_axi_DATA_AWADDR = 64'd0;

assign m_axi_DATA_AWBURST = 2'd0;

assign m_axi_DATA_AWCACHE = 4'd0;

assign m_axi_DATA_AWID = 1'd0;

assign m_axi_DATA_AWLEN = 32'd0;

assign m_axi_DATA_AWLOCK = 2'd0;

assign m_axi_DATA_AWPROT = 3'd0;

assign m_axi_DATA_AWQOS = 4'd0;

assign m_axi_DATA_AWREGION = 4'd0;

assign m_axi_DATA_AWSIZE = 3'd0;

assign m_axi_DATA_AWUSER = 1'd0;

assign m_axi_DATA_AWVALID = 1'b0;

assign m_axi_DATA_BREADY = 1'b0;

assign m_axi_DATA_RREADY = 1'b0;

assign m_axi_DATA_WDATA = {{{{ciphertext_load_reg_232}, {ciphertext_1_load_reg_237}}, {ciphertext_load_1_reg_242}}, {ciphertext_1_load_1_reg_247}};

assign m_axi_DATA_WID = 1'd0;

assign m_axi_DATA_WLAST = 1'b0;

assign m_axi_DATA_WSTRB = 4'd15;

assign m_axi_DATA_WUSER = 1'd0;

assign or_ln81_fu_160_p2 = (shl_ln79_fu_148_p2 | 3'd1);

assign shl_ln79_fu_148_p2 = ap_sig_allocacmp_i_2 << 3'd1;

assign zext_ln79_fu_154_p1 = shl_ln79_fu_148_p2;

assign zext_ln81_fu_166_p1 = or_ln81_fu_160_p2;

endmodule //aes128_top_aes128_top_Pipeline_STORE_DATA
